/**
 * 이름 원본 데이터 (이름, 발음, 의미, 유명인)
 * 오행과 성격은 발음 기반으로 자동 생성됨
 */

import { getPhoneticElements } from "./phonetic";
import type { EnglishName } from "./nameDb";
import type { Element } from "./saju";

// [이름, 한글발음, 의미, 유명인]
type RawName = [string, string, string, string];

const MEANING_ELEMENT_KEYWORDS: Record<Element, string[]> = {
  wood: ["나무", "숲", "풀", "잎", "꽃", "봄", "성장", "자연", "생명", "덩굴", "뿌리", "가지", "씨앗"],
  fire: ["빛", "불", "태양", "별", "새벽", "열정", "밝", "빛나", "횃불", "여름", "화", "광선", "불꽃"],
  earth: ["땅", "돌", "바위", "산", "대지", "흙", "안정", "보석", "토", "중심", "뿌리", "기반"],
  metal: ["금", "은", "철", "칼", "검", "왕", "전사", "수호", "강한", "승리", "힘", "정의", "고귀", "지배"],
  water: ["물", "바다", "강", "비", "호수", "이슬", "파도", "안개", "달", "밤", "지혜", "깊", "흐"],
};

const ELEMENT_PERSONALITIES: Record<Element, string[]> = {
  wood: ["창의적이고 자유로운", "성장하는 에너지의", "생명력 넘치는", "유연하고 적응력 있는", "개척하는 도전적인"],
  fire: ["열정적이고 밝은", "카리스마 넘치는", "에너지가 넘치는", "따뜻하고 활기찬", "빛나고 매력적인"],
  earth: ["안정적이고 신뢰감 있는", "포용력 있고 따뜻한", "성실하고 꼼꼼한", "든든하고 차분한", "지적이고 현명한"],
  metal: ["강인하고 결단력 있는", "정의롭고 리더십 있는", "당당하고 카리스마 있는", "고귀하고 품격 있는", "날카롭고 지적인"],
  water: ["깊이 있고 지혜로운", "자유롭고 직관적인", "신비롭고 매력적인", "맑고 순수한", "유연하고 깊은"],
};

function getMeaningElement(meaning: string): Element | null {
  for (const [el, keywords] of Object.entries(MEANING_ELEMENT_KEYWORDS) as [Element, string[]][]) {
    for (const kw of keywords) {
      if (meaning.includes(kw)) return el;
    }
  }
  return null;
}

function buildEnglishName(raw: RawName, gender: "male" | "female"): EnglishName {
  const [name, pronunciation, meaning, celebrity] = raw;

  // 1차: 발음 기반 오행
  const phoneticEls = getPhoneticElements(name);

  // 2차: 의미 기반 오행 추가
  const meaningEl = getMeaningElement(meaning);
  const elements: Element[] = [...phoneticEls];
  if (meaningEl && !elements.includes(meaningEl)) {
    elements.push(meaningEl);
  }
  // 최대 2개
  const finalElements = elements.slice(0, 2);
  if (finalElements.length === 0) finalElements.push("earth");

  // 성격: 주 오행 기반 랜덤 선택
  const primaryEl = finalElements[0];
  const personalities = ELEMENT_PERSONALITIES[primaryEl];
  const pIdx = hashSimple(name) % personalities.length;
  const personality = personalities[pIdx];

  return { name, pronunciation, gender, meaning, elements: finalElements, personality, celebrity };
}

function hashSimple(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

// ═══════════════════════════════════
//        남자 이름 원본 데이터
// ═══════════════════════════════════
const MALE_RAW: RawName[] = [
  ["Liam", "리암", "강한 의지의 전사", "Liam Hemsworth (배우)"],
  ["Noah", "노아", "평화와 안식", "Noah Centineo (배우)"],
  ["Oliver", "올리버", "올리브 나무, 평화", "Oliver Stone (감독)"],
  ["Elijah", "일라이자", "신의 힘", "Elijah Wood (배우)"],
  ["James", "제임스", "강한 리더", "James Dean (배우)"],
  ["William", "윌리엄", "강한 수호자", "Prince William (왕세자)"],
  ["Benjamin", "벤자민", "행운의 아들", "Benjamin Franklin (정치인)"],
  ["Lucas", "루카스", "빛을 가져오는 자", "George Lucas (감독)"],
  ["Henry", "헨리", "가정의 통치자", "Henry Cavill (배우)"],
  ["Alexander", "알렉산더", "인류의 수호자", "Alexander the Great (대왕)"],
  ["Mason", "메이슨", "돌을 다루는 장인", "Mason Mount (축구선수)"],
  ["Michael", "마이클", "신과 같은 자", "Michael Jordan (농구선수)"],
  ["Ethan", "이든", "강하고 굳건한", "Ethan Hawke (배우)"],
  ["Daniel", "다니엘", "신의 심판자", "Daniel Craig (배우)"],
  ["Jacob", "제이콥", "뒤따르는 자", "Jacob Elordi (배우)"],
  ["Logan", "로건", "작은 골짜기", "Hugh Jackman (배우)"],
  ["Jackson", "잭슨", "잭의 아들", "Jackson Wang (가수)"],
  ["Aiden", "에이든", "작은 불꽃", "Aiden Turner (배우)"],
  ["Sebastian", "세바스찬", "숭고한 자", "Sebastian Stan (배우)"],
  ["Matthew", "매튜", "신의 선물", "Matthew McConaughey (배우)"],
  ["Jack", "잭", "신의 은혜", "Jack Black (배우)"],
  ["Owen", "오웬", "젊은 전사", "Owen Wilson (배우)"],
  ["Ryan", "라이언", "작은 왕", "Ryan Reynolds (배우)"],
  ["Leo", "레오", "사자, 용맹한", "Leonardo DiCaprio (배우)"],
  ["Dylan", "딜런", "바다의 아들", "Bob Dylan (뮤지션)"],
  ["Luke", "루크", "빛의 전달자", "Luke Skywalker (캐릭터)"],
  ["Wyatt", "와이엇", "용감한 전사", "Wyatt Russell (배우)"],
  ["Carter", "카터", "수레를 모는 자", "Aaron Carter (가수)"],
  ["Julian", "줄리안", "젊은, 부드러운", "Julian Casablancas (뮤지션)"],
  ["Grayson", "그레이슨", "관리인의 아들", "Grayson Allen (농구선수)"],
  ["Isaac", "아이작", "웃음, 기쁨", "Isaac Newton (과학자)"],
  ["Joshua", "조슈아", "신은 구원이다", "Joshua Tree (자연)"],
  ["Andrew", "앤드류", "남자다운 강한", "Andrew Garfield (배우)"],
  ["Lincoln", "링컨", "호수 마을", "Abraham Lincoln (대통령)"],
  ["Nathan", "네이선", "신이 주신 자", "Nathan Drake (캐릭터)"],
  ["Caleb", "케일럽", "충실한 헌신", "Caleb McLaughlin (배우)"],
  ["Christian", "크리스천", "그리스도를 따르는", "Christian Bale (배우)"],
  ["Hunter", "헌터", "사냥꾼", "Hunter Biden (정치인)"],
  ["Connor", "코너", "강한 의지의 사냥개", "Connor McGregor (격투기)"],
  ["Adrian", "에이드리언", "아드리아 해의 자", "Adrian Grenier (배우)"],
  ["Eli", "엘라이", "높은, 승천하는", "Eli Manning (미식축구)"],
  ["Thomas", "토마스", "쌍둥이", "Thomas Edison (발명가)"],
  ["Aaron", "아론", "높은 산", "Aaron Paul (배우)"],
  ["Landon", "랜던", "긴 언덕", "Landon Donovan (축구선수)"],
  ["Cameron", "카메론", "구부러진 코", "James Cameron (감독)"],
  ["Austin", "오스틴", "위대한, 장엄한", "Austin Butler (배우)"],
  ["Nicholas", "니콜라스", "국민의 승리", "Nicholas Cage (배우)"],
  ["Dominic", "도미닉", "주님의", "Dominic Toretto (캐릭터)"],
  ["Brandon", "브랜든", "빗자루 언덕", "Brandon Lee (배우)"],
  ["Kai", "카이", "바다", "Kai (엑소)"],
  ["Zachary", "재커리", "신이 기억하는", "Zachary Levi (배우)"],
  ["Cooper", "쿠퍼", "통 만드는 장인", "Bradley Cooper (배우)"],
  ["Parker", "파커", "공원 관리인", "Peter Parker (캐릭터)"],
  ["Miles", "마일스", "자비로운 군인", "Miles Davis (뮤지션)"],
  ["Sawyer", "소여", "나무꾼", "Tom Sawyer (캐릭터)"],
  ["Jason", "제이슨", "치유하는 자", "Jason Momoa (배우)"],
  ["Declan", "데클런", "선한 사람", "Declan Rice (축구선수)"],
  ["Weston", "웨스턴", "서쪽 마을", "Weston McKennie (축구선수)"],
  ["Easton", "이스턴", "동쪽 마을", "Easton Corbin (가수)"],
  ["Colton", "콜턴", "석탄 마을", "Colton Haynes (배우)"],
  ["Bryson", "브라이슨", "귀족의 아들", "Bryson Tiller (래퍼)"],
  ["Felix", "펠릭스", "행운의, 행복한", "Felix Hernandez (야구선수)"],
  ["Hugo", "휴고", "영혼, 지성", "Victor Hugo (작가)"],
  ["Ray", "레이", "빛줄기, 광선", "Ray Charles (뮤지션)"],
  ["Arthur", "아서", "곰처럼 강한", "King Arthur (전설)"],
  ["Oscar", "오스카", "신의 창", "Oscar Wilde (작가)"],
  ["Victor", "빅터", "승리자", "Victor Hugo (작가)"],
  ["Sean", "숀", "신의 은총", "Sean Connery (배우)"],
  ["Marcus", "마커스", "전쟁의 신", "Marcus Aurelius (황제)"],
  ["Grant", "그랜트", "위대한", "Cary Grant (배우)"],
  ["Patrick", "패트릭", "귀족, 고귀한", "Patrick Swayze (배우)"],
  ["Finn", "핀", "공정한 사람", "Finn Wolfhard (배우)"],
  ["Brooks", "브룩스", "시냇물 근처", "Brooks Robinson (야구선수)"],
  ["River", "리버", "강, 흐르는 물", "River Phoenix (배우)"],
  ["Phoenix", "피닉스", "불사조", "Joaquin Phoenix (배우)"],
  ["Blaze", "블레이즈", "불꽃", "Blaze Bayley (뮤지션)"],
  ["Forest", "포레스트", "숲의 수호자", "Forest Whitaker (배우)"],
  ["Reed", "리드", "갈대, 유연한", "Reed Richards (캐릭터)"],
  ["Clay", "클레이", "점토, 대지", "Clay Aiken (가수)"],
  ["Sterling", "스털링", "순수한 은", "Sterling K. Brown (배우)"],
  ["Rowan", "로완", "마가목 나무", "Rowan Atkinson (배우)"],
  ["Jasper", "재스퍼", "보석의 선물", "Jasper Johns (아티스트)"],
  ["Asher", "애셔", "행복한, 축복받은", "Asher Angel (배우)"],
  ["Silas", "사일러스", "숲의 사람", "Silas Marner (캐릭터)"],
  ["Nile", "나일", "생명의 강", "Nile Rodgers (뮤지션)"],
  ["Wade", "웨이드", "강을 건너는", "Dwyane Wade (농구선수)"],
  ["Marshall", "마샬", "말 관리인", "Marshall Mathers (래퍼)"],
  ["Griffin", "그리핀", "강한 군주", "Griffin (신화 생물)"],
  ["Tristan", "트리스탄", "용감한 기사", "Tristan Thompson (농구선수)"],
  ["Axel", "악셀", "평화의 아버지", "Axl Rose (뮤지션)"],
  ["Cedric", "세드릭", "전투의 리더", "Cedric Diggory (캐릭터)"],
  ["Apollo", "아폴로", "태양의 신", "Apollo Creed (캐릭터)"],
  ["Dante", "단테", "인내하는 자", "Dante Alighieri (시인)"],
  ["Cyrus", "사이러스", "태양, 왕좌", "Cyrus the Great (왕)"],
  ["Elio", "엘리오", "태양", "Elio (영화 캐릭터)"],
  ["Sol", "솔", "태양", "Sol Campbell (축구선수)"],
  ["Ravi", "라비", "태양", "Ravi Shankar (음악가)"],
  ["Caspian", "카스피안", "카스피해", "Prince Caspian (캐릭터)"],
  ["Merlin", "멀린", "바다의 요새", "Merlin (전설)"],
  ["Kendrick", "켄드릭", "왕의 힘", "Kendrick Lamar (래퍼)"],
  ["Beckett", "베켓", "시냇물 근처", "Samuel Beckett (극작가)"],
  ["Dorian", "도리안", "바다에서 온 자", "Dorian Gray (캐릭터)"],
  ["Kelvin", "켈빈", "좁은 강", "Lord Kelvin (물리학자)"],
  ["Tate", "테이트", "쾌활한", "Tate Modern (미술관)"],
  ["Spencer", "스펜서", "관리인", "Spencer Tracy (배우)"],
  ["Max", "맥스", "가장 위대한", "Max Verstappen (F1)"],
  ["Chase", "체이스", "사냥꾼", "Chase Crawford (배우)"],
  ["Gavin", "개빈", "흰 매", "Gavin Rossdale (뮤지션)"],
  ["Derek", "데릭", "통치자", "Derek Jeter (야구선수)"],
  ["Warren", "워렌", "수호자", "Warren Buffett (투자가)"],
  ["Brock", "브록", "오소리, 바위", "Brock Lesnar (레슬러)"],
  ["Travis", "트래비스", "길을 건너는", "Travis Scott (뮤지션)"],
  ["Glenn", "글렌", "좁은 골짜기", "Glenn Close (배우)"],
  ["Carl", "칼", "자유로운 남자", "Carl Sagan (천문학자)"],
  ["Everett", "에버렛", "멧돼지처럼 강한", "Everett McGill (배우)"],
  ["Hector", "헥터", "지키는 자", "Hector (트로이 전쟁)"],
  ["Ivan", "이반", "신의 은총", "Ivan the Great (대제)"],
  ["Roland", "롤랜드", "유명한 땅", "Roland (프랑스 전설)"],
  ["Conrad", "콘래드", "용감한 조언자", "Joseph Conrad (작가)"],
  ["Pierce", "피어스", "바위, 관통하는", "Pierce Brosnan (배우)"],
  ["Rex", "렉스", "왕", "Rex Harrison (배우)"],
  ["Kenneth", "케네스", "잘생긴, 불의", "Kenneth Branagh (배우)"],
  ["Flynn", "플린", "붉은 머리의 아들", "Errol Flynn (배우)"],
  ["Nico", "니코", "승리의 사람", "Nico Rosberg (F1)"],
  ["Theo", "테오", "신의 선물", "Theo James (배우)"],
  ["Murphy", "머피", "바다의 전사", "Eddie Murphy (배우)"],
  ["Douglas", "더글라스", "어두운 물", "Douglas Adams (작가)"],
  ["Irving", "어빙", "바다의 친구", "Irving Berlin (작곡가)"],
  ["Monroe", "먼로", "강 어귀", "James Monroe (대통령)"],
  ["Nolan", "놀런", "고귀한, 유명한", "Christopher Nolan (감독)"],
  ["Linden", "린든", "보리수나무", "Lyndon Johnson (대통령)"],
  ["Palmer", "팔머", "야자수의 자", "Arnold Palmer (골프)"],
  ["Vernon", "버논", "오리나무 숲", "Vernon (세븐틴)"],
  ["Garrett", "개럿", "창으로 다스리는", "Garrett Hedlund (배우)"],
  ["Leif", "레이프", "후계자, 잎", "Leif Erikson (탐험가)"],
  ["Bryce", "브라이스", "민첩한", "Bryce Dallas Howard (배우)"],
  ["Heath", "히스", "황야, 들판", "Heath Ledger (배우)"],
  ["Orion", "오라이온", "사냥꾼 별자리", "Orion (신화)"],
  ["Alden", "올든", "오래된 친구", "Alden Ehrenreich (배우)"],
  ["Burke", "버크", "요새의 자", "Edmund Burke (정치가)"],
  ["Craig", "크레이그", "바위", "Daniel Craig (배우)"],
  ["Ellis", "엘리스", "자비로운", "Ellis Island (역사)"],
  ["Gareth", "가레스", "온화한", "Gareth Bale (축구)"],
  ["Sylvan", "실반", "숲의 사람", "Sylvan Esso (뮤지션)"],
  ["Lucian", "루시안", "빛의 사람", "Lucian Freud (화가)"],
  ["Hayden", "헤이든", "불의 골짜기", "Hayden Christensen (배우)"],
  ["Ashton", "애슈턴", "물푸레 마을", "Ashton Kutcher (배우)"],
  ["Dustin", "더스틴", "용감한 전사의 돌", "Dustin Hoffman (배우)"],
  ["Clayton", "클레이턴", "점토 마을", "Clayton Kershaw (야구)"],
  ["Seth", "세스", "지정된 자", "Seth Rogen (배우)"],
  ["Perry", "페리", "배나무", "Katy Perry (가수)"],
  ["Lance", "랜스", "창, 무기", "Lance Armstrong (사이클)"],
  ["Trent", "트렌트", "강을 건너는 자", "Trent Reznor (뮤지션)"],
  ["Phillip", "필립", "말을 사랑하는", "Prince Philip (왕배)"],
  ["Emmett", "에밋", "진실의 강한 자", "Emmett Brown (캐릭터)"],
  ["Wesley", "웨슬리", "서쪽 초원", "Wesley Snipes (배우)"],
  ["Drake", "드레이크", "용, 수컷 오리", "Drake (래퍼)"],
  ["Blake", "블레이크", "검은, 밝은", "Blake Lively (배우)"],
  ["Cole", "콜", "숯, 검은", "Cole Sprouse (배우)"],
  ["Damian", "데이미언", "길들이는 자", "Damian Lillard (농구)"],
  ["Tyler", "타일러", "타일 깔는 자", "Tyler Perry (감독)"],
  ["Jace", "제이스", "치유하는 자", "Jace Norman (배우)"],
  ["Xavier", "자비에르", "밝은 새 집", "Xavier Dolan (감독)"],
  ["Zane", "제인", "신의 은혜", "Zane Malik (가수)"],
  ["Atlas", "아틀라스", "하늘을 짊어진", "Atlas (신화)"],
  ["Milo", "마일로", "자비로운, 병사", "Milo Ventimiglia (배우)"],
  ["Vincent", "빈센트", "정복하는 자", "Vincent van Gogh (화가)"],
  ["Theodore", "테오도어", "신의 선물", "Theodore Roosevelt (대통령)"],
  ["August", "오거스트", "위대한, 장엄한", "August Wilson (극작가)"],
  ["Harrison", "해리슨", "해리의 아들", "Harrison Ford (배우)"],
  ["Jasiah", "제시아", "신이 치유하심", "Jasiah (뮤지션)"],
  ["Maverick", "매버릭", "독립적인 자", "Top Gun Maverick (영화)"],
  ["Knox", "녹스", "둥근 언덕", "Knox Jolie-Pitt (유명인)"],
  ["Hendrix", "헨드릭스", "집의 통치자", "Jimi Hendrix (기타리스트)"],
  ["Bodhi", "보디", "깨달음", "Bodhi (영화 캐릭터)"],
  ["Cruz", "크루즈", "십자가", "Cruz Beckham (유명인)"],
  ["Kingsley", "킹슬리", "왕의 초원", "Ben Kingsley (배우)"],
  ["Zion", "자이온", "약속의 땅", "Zion Williamson (농구)"],
  ["Legend", "레전드", "전설", "John Legend (가수)"],
  ["Arlo", "알로", "요새 언덕", "Arlo Guthrie (뮤지션)"],
  ["Rhett", "레트", "열정적인 조언자", "Rhett Butler (캐릭터)"],
  ["Atticus", "아티커스", "아테네의 사람", "Atticus Finch (캐릭터)"],
  ["Callum", "캘럼", "비둘기", "Callum Turner (배우)"],
  ["Ezra", "에즈라", "도움, 돕는 자", "Ezra Miller (배우)"],
  ["Roman", "로만", "로마의 시민", "Roman Reigns (레슬러)"],
  ["Jude", "주드", "칭송받는 자", "Jude Law (배우)"],
  ["Atlas", "아틀라스", "지구를 받치는 자", "Atlas (그리스 신화)"],
  ["Kai", "카이", "바다, 용서", "Kai (엑소)"],
  ["Mateo", "마테오", "신의 선물", "Mateo Kovacic (축구)"],
  ["Levi", "리바이", "연합된, 결합된", "Levi Ackerman (캐릭터)"],
  ["Archer", "아처", "궁수", "Archer (애니메이션)"],
  ["Micah", "마이카", "신과 같은 자", "Micah Richards (축구)"],
  ["Elias", "엘리아스", "신은 나의 주", "Elias Pettersson (하키)"],
  ["Hudson", "허드슨", "마음의 아들", "Hudson River (지명)"],
  ["Ezekiel", "이지키엘", "신이 강하게 하심", "Ezekiel Elliott (미식축구)"],
  ["Malachi", "말라키", "신의 전령", "Malachi (성경)"],
  ["Braxton", "브랙스턴", "브록의 마을", "Braxton Miller (미식축구)"],
  ["Zander", "잰더", "인류의 수호자", "Zander Murray (축구)"],
  ["Rafael", "라파엘", "신이 치유하심", "Rafael Nadal (테니스)"],
  ["Bennett", "베넷", "축복받은 작은 자", "Bennett Miller (감독)"],
  ["Ronan", "로넌", "맹세, 약속", "Saoirse Ronan (배우)"],
  ["Gage", "게이지", "맹세, 측정자", "Gage Munroe (배우)"],
  ["Jensen", "젠센", "신의 은혜의 아들", "Jensen Ackles (배우)"],
  ["Riley", "라일리", "용감한", "Riley Curry (유명인)"],
  ["Anderson", "앤더슨", "앤드류의 아들", "Anderson Cooper (앵커)"],
  ["Maxwell", "맥스웰", "위대한 샘물", "Maxwell (뮤지션)"],
  ["Lennox", "레녹스", "느릅나무 숲", "Lewis Lennox (배우)"],
];

// ═══════════════════════════════════
//        여자 이름 원본 데이터
// ═══════════════════════════════════
const FEMALE_RAW: RawName[] = [
  ["Emma", "엠마", "전체적인, 보편적인", "Emma Watson (배우)"],
  ["Olivia", "올리비아", "올리브 나무, 평화", "Olivia Rodrigo (가수)"],
  ["Ava", "에이바", "생명, 숨결", "Ava Gardner (배우)"],
  ["Isabella", "이사벨라", "신에게 헌신한", "Isabella Rossellini (배우)"],
  ["Sophia", "소피아", "지혜", "Sophia Loren (배우)"],
  ["Mia", "미아", "나의 사랑", "Mia Farrow (배우)"],
  ["Charlotte", "샬롯", "자유로운 여성", "Charlotte Brontë (작가)"],
  ["Amelia", "아멜리아", "근면한, 노력하는", "Amelia Earhart (비행사)"],
  ["Harper", "하퍼", "하프 연주자", "Harper Lee (작가)"],
  ["Evelyn", "에블린", "생명, 빛", "Evelyn Hugo (캐릭터)"],
  ["Abigail", "아비게일", "아버지의 기쁨", "Abigail Adams (영부인)"],
  ["Emily", "에밀리", "열심히 노력하는", "Emily Blunt (배우)"],
  ["Ella", "엘라", "아름다운 요정", "Ella Fitzgerald (가수)"],
  ["Elizabeth", "엘리자베스", "신의 맹세", "Queen Elizabeth (여왕)"],
  ["Camila", "카밀라", "예배의 시중", "Camila Cabello (가수)"],
  ["Luna", "루나", "달, 밤의 빛", "Luna Lovegood (캐릭터)"],
  ["Sofia", "소피아", "지혜로운 자", "Sofia Vergara (배우)"],
  ["Avery", "에이버리", "요정의 통치자", "Avery Bradley (농구)"],
  ["Mila", "밀라", "사랑스러운, 은총", "Mila Kunis (배우)"],
  ["Aria", "아리아", "노래, 멜로디", "Aria (오페라)"],
  ["Scarlett", "스칼렛", "붉은색, 강렬한", "Scarlett Johansson (배우)"],
  ["Penelope", "페넬로피", "베 짜는 여인", "Penelope Cruz (배우)"],
  ["Layla", "레일라", "밤, 어둠의 미인", "Layla (노래)"],
  ["Chloe", "클로이", "푸른 새싹", "Chloe Kim (스노보드)"],
  ["Victoria", "빅토리아", "승리", "Victoria Beckham (디자이너)"],
  ["Madison", "매디슨", "전사의 아들", "Madison Beer (가수)"],
  ["Eleanor", "엘리노어", "빛나는 자", "Eleanor Roosevelt (영부인)"],
  ["Grace", "그레이스", "우아함, 은총", "Grace Kelly (왕비)"],
  ["Nora", "노라", "빛, 명예", "Nora Jones (뮤지션)"],
  ["Riley", "라일리", "용감한 자", "Riley Keough (배우)"],
  ["Zoey", "조이", "생명", "Zoey Deutch (배우)"],
  ["Hannah", "한나", "은총, 자비", "Hannah Arendt (철학자)"],
  ["Hazel", "헤이즐", "개암나무, 지혜", "Hazel Scott (피아니스트)"],
  ["Lily", "릴리", "백합, 순수한", "Lily Collins (배우)"],
  ["Ellie", "엘리", "빛나는 자", "Ellie Goulding (가수)"],
  ["Violet", "바이올렛", "제비꽃, 보라색", "Violet Crawley (캐릭터)"],
  ["Lillian", "릴리안", "순수한 백합", "Lillian Hellman (작가)"],
  ["Zoe", "조이", "생명", "Zoe Saldana (배우)"],
  ["Stella", "스텔라", "별, 빛나는", "Stella McCartney (디자이너)"],
  ["Aurora", "오로라", "새벽빛", "Aurora (가수)"],
  ["Natalie", "나탈리", "크리스마스에 태어난", "Natalie Portman (배우)"],
  ["Emilia", "에밀리아", "열심히 노력하는", "Emilia Clarke (배우)"],
  ["Leah", "레아", "지친, 자연의", "Leah (성경)"],
  ["Aubrey", "오브리", "요정의 통치자", "Aubrey Plaza (배우)"],
  ["Willow", "윌로우", "버드나무, 유연한", "Willow Smith (가수)"],
  ["Addison", "애디슨", "아담의 아들", "Addison Rae (인플루언서)"],
  ["Lucy", "루시", "빛", "Lucy Liu (배우)"],
  ["Audrey", "오드리", "고귀한 힘", "Audrey Hepburn (배우)"],
  ["Bella", "벨라", "아름다운", "Bella Hadid (모델)"],
  ["Nova", "노바", "새로운 별", "Nova (천문학)"],
  ["Brooklyn", "브루클린", "물과 땅", "Brooklyn Beckham (유명인)"],
  ["Paisley", "페이즐리", "교회, 성지", "Paisley Park (음악)"],
  ["Savannah", "사바나", "넓은 초원", "Savannah Guthrie (앵커)"],
  ["Claire", "클레어", "밝은, 명확한", "Claire Danes (배우)"],
  ["Skylar", "스카일라", "하늘의 보호자", "Skylar Grey (가수)"],
  ["Isla", "아일라", "섬, 고요한 물", "Isla Fisher (배우)"],
  ["Genesis", "제네시스", "시작, 기원", "Genesis (밴드)"],
  ["Naomi", "나오미", "즐거운, 아름다운", "Naomi Campbell (모델)"],
  ["Elena", "엘레나", "빛나는, 햇빛", "Elena Ferrante (작가)"],
  ["Caroline", "캐롤라인", "자유로운 여성", "Caroline Kennedy (정치인)"],
  ["Anna", "안나", "우아한", "Anna Karenina (캐릭터)"],
  ["Maya", "마야", "환상, 대지의 어머니", "Maya Angelou (시인)"],
  ["Valentina", "발렌티나", "강한, 건강한", "Valentina Tereshkova (우주인)"],
  ["Ruby", "루비", "붉은 보석", "Ruby Rose (배우)"],
  ["Kennedy", "케네디", "투구 쓴 리더", "Kennedy (정치 가문)"],
  ["Ivy", "아이비", "담쟁이, 끈기", "Blue Ivy Carter (유명인)"],
  ["Ariana", "아리아나", "가장 거룩한", "Ariana Grande (가수)"],
  ["Aaliyah", "알리야", "높은, 숭고한", "Aaliyah (가수)"],
  ["Cora", "코라", "소녀, 처녀", "Cora (다운튼 애비)"],
  ["Madelyn", "매들린", "높은 탑의 여인", "Madelyn Cline (배우)"],
  ["Alice", "앨리스", "고귀한", "Alice in Wonderland (캐릭터)"],
  ["Hailey", "헤일리", "건초 초원", "Hailey Bieber (모델)"],
  ["Gabriella", "가브리엘라", "신의 전사", "Gabriella Montez (캐릭터)"],
  ["Allison", "앨리슨", "고귀한 종류의", "Allison Williams (배우)"],
  ["Gianna", "지아나", "신의 은총", "Gianna Bryant (유명인)"],
  ["Serenity", "세레니티", "고요, 평화", "Serenity (영화)"],
  ["Samantha", "사만다", "경청하는 자", "Samantha Jones (캐릭터)"],
  ["Sarah", "세라", "공주", "Sarah Jessica Parker (배우)"],
  ["Autumn", "오텀", "가을, 풍요", "Autumn Phillips (왕실)"],
  ["Quinn", "퀸", "지혜로운 리더", "Quinn (글리)"],
  ["Eva", "에바", "생명", "Eva Longoria (배우)"],
  ["Piper", "파이퍼", "피리 부는 사람", "Piper Chapman (캐릭터)"],
  ["Sophie", "소피", "지혜", "Sophie Turner (배우)"],
  ["Sadie", "세이디", "공주", "Sadie Sink (배우)"],
  ["Delilah", "딜라일라", "섬세한, 약한", "Delilah (노래)"],
  ["Josephine", "조세핀", "신이 더하심", "Josephine Baker (가수)"],
  ["Adeline", "아델라인", "고귀한, 친절한", "Adeline Virginia Woolf (작가)"],
  ["Arya", "아리아", "고귀한 여신", "Arya Stark (캐릭터)"],
  ["Emery", "에머리", "근면한 리더", "Emery (밴드)"],
  ["Lydia", "리디아", "아름다운 자", "Lydia (성경)"],
  ["Clara", "클라라", "밝은, 명확한", "Clara Schumann (피아니스트)"],
  ["Vivian", "비비안", "생명이 넘치는", "Vivian Leigh (배우)"],
  ["Madeline", "매들린", "높은 탑", "Madeline (캐릭터)"],
  ["Peyton", "페이턴", "전사의 마을", "Peyton Manning (미식축구)"],
  ["Julia", "줄리아", "젊은, 부드러운", "Julia Roberts (배우)"],
  ["Brielle", "브리엘", "신은 나의 힘", "Brielle Biermann (유명인)"],
  ["Reagan", "레이건", "작은 왕", "Ronald Reagan (대통령)"],
  ["Jade", "제이드", "옥, 고귀한 보석", "Jade Thirlwall (가수)"],
  ["Melody", "멜로디", "노래, 음악", "Melody (디즈니)"],
  ["Athena", "아테나", "지혜의 여신", "Athena (그리스 신화)"],
  ["Lila", "라일라", "밤, 아름다운", "Lila Moss (모델)"],
  ["Iris", "아이리스", "무지개, 전령", "Iris Apfel (패션 아이콘)"],
  ["Maria", "마리아", "바다의 별", "Maria Sharapova (테니스)"],
  ["Diana", "다이애나", "신성한, 달의 여신", "Princess Diana (왕세자비)"],
  ["Marina", "마리나", "바다에서 온 자", "Marina Abramović (아티스트)"],
  ["Brooke", "브룩", "시냇물", "Brooke Shields (배우)"],
  ["Serena", "세레나", "고요한, 평화로운", "Serena Williams (테니스)"],
  ["Pearl", "펄", "진주, 바다의 보석", "Pearl Bailey (가수)"],
  ["Coral", "코랄", "산호, 바다의 보석", "Coral (자연)"],
  ["Misty", "미스티", "안개, 신비로운", "Misty Copeland (발레리나)"],
  ["Flora", "플로라", "꽃의 여신", "Flora (로마 신화)"],
  ["Dahlia", "달리아", "꽃, 우아함", "Black Dahlia (영화)"],
  ["Jasmine", "재스민", "재스민 꽃, 향기", "Princess Jasmine (알라딘)"],
  ["Holly", "홀리", "호랑가시나무", "Holly Hunter (배우)"],
  ["Fern", "펀", "양치식물, 진실함", "Fern (노매드랜드)"],
  ["Magnolia", "매그놀리아", "목련, 고귀한", "Magnolia (영화)"],
  ["Laurel", "로렐", "월계수, 승리의 관", "Laurel (코미디)"],
  ["Heather", "헤더", "히스꽃, 들판", "Heather Graham (배우)"],
  ["Rosemary", "로즈마리", "바다의 이슬", "Rosemary Clooney (가수)"],
  ["Gaia", "가이아", "대지의 여신", "Gaia (신화)"],
  ["Terra", "테라", "대지, 지구", "Terra (게임 캐릭터)"],
  ["Petra", "페트라", "바위, 굳건한", "Petra (고대 도시)"],
  ["Ruth", "루스", "친구, 동반자", "Ruth Bader Ginsburg (대법관)"],
  ["Martha", "마사", "여주인", "Martha Stewart (사업가)"],
  ["Adelaide", "애들레이드", "고귀한 성품", "Adelaide (도시)"],
  ["Gemma", "젬마", "보석", "Gemma Chan (배우)"],
  ["Tessa", "테사", "수확하는 사람", "Tessa Thompson (배우)"],
  ["Wren", "렌", "굴뚝새, 강인한", "Wren (새)"],
  ["Regina", "레지나", "여왕", "Regina King (배우)"],
  ["Freya", "프레이아", "사랑과 전쟁의 여신", "Freya (노르드 신화)"],
  ["Ingrid", "잉그리드", "아름다운 신", "Ingrid Bergman (배우)"],
  ["Zelda", "젤다", "행복한 전사", "Zelda (게임)"],
  ["Cassandra", "카산드라", "예언하는 자", "Cassandra (신화)"],
  ["Minerva", "미네르바", "지혜의 여신", "Minerva McGonagall (캐릭터)"],
  ["Beatrice", "베아트리체", "축복을 가져오는", "Beatrice (신곡)"],
  ["Cordelia", "코딜리아", "바다의 보석", "Cordelia (리어왕)"],
  ["Harriet", "해리엇", "가정의 통치자", "Harriet Tubman (인권운동가)"],
  ["Sabrina", "사브리나", "전설적인 공주", "Sabrina (영화)"],
  ["Sienna", "시에나", "따뜻한 갈색", "Sienna Miller (배우)"],
  ["Phoebe", "피비", "빛나는, 밝은", "Phoebe Waller-Bridge (배우)"],
  ["Ember", "엠버", "불씨, 잔불", "Amber (가수)"],
  ["Dawn", "던", "새벽, 시작", "Dawn French (배우)"],
  ["Lucia", "루시아", "빛", "Lucia (오페라)"],
  ["Celeste", "셀레스트", "하늘의, 천상의", "Celeste (가수)"],
  ["Helena", "헬레나", "빛나는 횃불", "Helena Bonham Carter (배우)"],
  ["Summer", "서머", "여름, 따뜻한", "Summer Glau (배우)"],
  ["Roxanne", "록산", "새벽빛, 밝은 별", "Roxanne (노래)"],
  ["Lyra", "라이라", "거문고자리, 음악", "Lyra (황금나침반)"],
  ["Seraphina", "세라피나", "불꽃의 천사", "Seraphina Affleck (유명인)"],
  ["Ariel", "아리엘", "바다의 공주", "Ariel (인어공주)"],
  ["Rain", "레인", "비, 생명의 물", "Rain (가수)"],
  ["Ondine", "온디네", "물의 정령", "Ondine (전설)"],
  ["Bay", "베이", "만, 월계수", "Bay (자연)"],
  ["Maren", "마렌", "바다의", "Maren Morris (가수)"],
  ["Cascade", "캐스케이드", "폭포", "Cascade (자연)"],
  ["Waverly", "웨이벌리", "흔들리는 초원", "Waverly (소설)"],
  ["Tallulah", "탈룰라", "뛰어오르는 물", "Tallulah Bankhead (배우)"],
  ["Delta", "델타", "강 삼각주", "Delta Goodrem (가수)"],
  ["Nerissa", "네리사", "바다의 요정", "Nerissa (베니스의 상인)"],
  ["Oceana", "오세아나", "바다", "Oceana (가수)"],
  ["Constance", "콘스탄스", "변치 않는", "Constance Wu (배우)"],
  ["Maxine", "맥신", "가장 위대한", "Maxine Waters (정치인)"],
  ["Isolde", "이졸데", "얼음의 전사", "Isolde (전설)"],
  ["Bridget", "브리짓", "강한, 높은", "Bridget Jones (캐릭터)"],
  ["Winifred", "위니프레드", "평화의 친구", "Winifred (영화)"],
  ["Eloise", "엘로이즈", "건강한, 넓은", "Eloise (소설)"],
  ["Margot", "마고", "진주", "Margot Robbie (배우)"],
  ["Millie", "밀리", "부지런한, 강한", "Millie Bobby Brown (배우)"],
  ["Thea", "테아", "여신, 신성한", "Thea Queen (캐릭터)"],
  ["Sunny", "서니", "햇살, 밝은", "Sunny (소녀시대)"],
  ["Ayla", "아일라", "달빛, 후광", "Ayla (캐릭터)"],
  ["Blaire", "블레어", "들판, 전장", "Blair Waldorf (캐릭터)"],
  ["Candace", "캔디스", "빛나는, 순수한", "Candace Cameron (배우)"],
  ["Valerie", "발레리", "강한, 용감한", "Valerie (노래)"],
  ["Gwendolyn", "그웬돌린", "하얀 원, 축복", "Gwen Stacy (캐릭터)"],
  ["Katrina", "카트리나", "순수한", "Katrina (자연)"],
  ["Eliana", "엘리아나", "신이 응답하심", "Eliana (가수)"],
  ["Kinsley", "킨슬리", "왕의 초원", "Kinsley (유명인)"],
  ["Lena", "레나", "빛나는 여인", "Lena Headey (배우)"],
  ["Vera", "베라", "진실, 믿음", "Vera Wang (디자이너)"],
  ["Nadia", "나디아", "희망", "Nadia Comaneci (체조)"],
  ["Kira", "키라", "빛의 여인", "Kira Knightley (배우)"],
  ["Daphne", "다프네", "월계수 나무", "Daphne (신화)"],
  ["Selena", "셀레나", "달의 여신", "Selena Gomez (가수)"],
  ["Bianca", "비앙카", "하얀, 순수한", "Bianca Jagger (유명인)"],
  ["Priscilla", "프리실라", "고대의, 오래된", "Priscilla Presley (배우)"],
  ["Esme", "에즈메", "사랑받는, 존경", "Esme (트와일라잇)"],
  ["Alma", "알마", "영혼, 친절한", "Alma (영화)"],
  ["Cleo", "클레오", "영광, 자부심", "Cleopatra (여왕)"],
  ["Maeve", "메이브", "취하게 하는 자", "Maeve (웨스트월드)"],
  ["Sasha", "사샤", "인류의 수호자", "Sasha Obama (유명인)"],
  ["Talia", "탈리아", "하늘의 이슬", "Talia Shire (배우)"],
  ["Winona", "위노나", "첫째 딸", "Winona Ryder (배우)"],
  ["Elsa", "엘사", "고귀한, 서약", "Elsa (겨울왕국)"],
  ["Anastasia", "아나스타시아", "부활", "Anastasia (영화)"],
  ["Fiona", "피오나", "공정한, 하얀", "Fiona Apple (가수)"],
  ["Giselle", "지젤", "맹세", "Gisele Bundchen (모델)"],
  ["Hope", "호프", "희망", "Hope Solo (축구)"],
  ["Joy", "조이", "기쁨", "Joy (레드벨벳)"],
  ["Paige", "페이지", "어린 시녀", "Paige (WWE)"],
  ["Sloane", "슬론", "전사", "Sloane Stephens (테니스)"],
  ["Teagan", "티건", "아름다운 시인", "Tegan (가수)"],
  ["Zara", "자라", "공주, 꽃", "Zara Phillips (왕실)"],
  ["Maisie", "메이지", "진주, 빛의 아이", "Maisie Williams (배우)"],
  ["Elsie", "엘시", "고귀한, 서약", "Elsie Fisher (배우)"],
  ["Sage", "세이지", "현명한, 허브", "Sage (허브)"],
  ["Willa", "윌라", "결의의 보호자", "Willa Holland (배우)"],
  ["Poppy", "포피", "양귀비 꽃", "Poppy Delevingne (모델)"],
  ["Annie", "애니", "은총, 기도", "Annie Hall (영화)"],
  ["Nyla", "나일라", "승리자", "Nyla Rose (레슬러)"],
  ["Remi", "레미", "노 젓는 자", "Remi Wolf (가수)"],
  ["Harlow", "할로우", "바위 언덕", "Jean Harlow (배우)"],
  ["Lola", "롤라", "슬픔의 여인", "Lola Bunny (캐릭터)"],
  ["Milana", "밀라나", "사랑스러운", "Milana Vayntrub (배우)"],
  ["Nessa", "네사", "순수한 자", "Nessa Barrett (가수)"],
  ["Estelle", "에스텔", "별", "Estelle (가수)"],
  ["Colette", "콜레트", "승리의 백성", "Colette (작가)"],
  ["Marlowe", "말로우", "유목지 언덕", "Christopher Marlowe (극작가)"],
  ["Juliette", "줄리엣", "젊은, 사랑의", "Juliette Binoche (배우)"],
];

// 빌드 함수
export function buildAllNames(): EnglishName[] {
  const males = MALE_RAW.map((r) => buildEnglishName(r, "male"));
  const females = FEMALE_RAW.map((r) => buildEnglishName(r, "female"));
  return [...males, ...females];
}
