import type { Element } from "./saju";

export interface EnglishName {
  name: string;
  pronunciation: string; // 한글 발음
  gender: "male" | "female" | "unisex";
  meaning: string; // 이름 의미/어원
  elements: Element[]; // 매칭 오행 (1~2개)
  personality: string; // 성격 이미지
  celebrity: string; // 유명인 동명
}

export const NAME_DB: EnglishName[] = [
  // ─── 목(木) — 성장, 창의력, 자연 ───
  {
    name: "Oliver",
    pronunciation: "올리버",
    gender: "male",
    meaning: "올리브 나무, 평화의 상징",
    elements: ["wood"],
    personality: "자유롭고 창의적인",
    celebrity: "Oliver Stone (영화감독)",
  },
  {
    name: "Sylvia",
    pronunciation: "실비아",
    gender: "female",
    meaning: "숲, 자연에서 온 사람",
    elements: ["wood"],
    personality: "자연을 사랑하는 감성적인",
    celebrity: "Sylvia Plath (시인)",
  },
  {
    name: "Ashley",
    pronunciation: "애슐리",
    gender: "female",
    meaning: "물푸레나무 숲",
    elements: ["wood"],
    personality: "밝고 생기 넘치는",
    celebrity: "Ashley Graham (모델)",
  },
  {
    name: "Forest",
    pronunciation: "포레스트",
    gender: "male",
    meaning: "숲, 자연의 수호자",
    elements: ["wood"],
    personality: "깊이 있고 사려 깊은",
    celebrity: "Forest Whitaker (배우)",
  },
  {
    name: "Ivy",
    pronunciation: "아이비",
    gender: "female",
    meaning: "담쟁이, 끈기와 성장",
    elements: ["wood"],
    personality: "강인하고 끈기 있는",
    celebrity: "Beyoncé의 딸 Blue Ivy",
  },
  {
    name: "Liam",
    pronunciation: "리암",
    gender: "male",
    meaning: "강한 의지의 전사",
    elements: ["wood", "metal"],
    personality: "용감하고 결단력 있는",
    celebrity: "Liam Neeson (배우)",
  },
  {
    name: "Hazel",
    pronunciation: "헤이즐",
    gender: "female",
    meaning: "개암나무, 지혜",
    elements: ["wood", "earth"],
    personality: "따뜻하고 지혜로운",
    celebrity: "Hazel Scott (재즈 피아니스트)",
  },
  {
    name: "Logan",
    pronunciation: "로건",
    gender: "male",
    meaning: "작은 골짜기",
    elements: ["wood", "earth"],
    personality: "자유분방하고 독립적인",
    celebrity: "Hugh Jackman (로건 역)",
  },

  // ─── 화(火) — 열정, 리더십, 빛 ───
  {
    name: "Lucas",
    pronunciation: "루카스",
    gender: "male",
    meaning: "빛, 밝음을 가져오는 사람",
    elements: ["fire"],
    personality: "밝고 에너지 넘치는",
    celebrity: "George Lucas (영화감독)",
  },
  {
    name: "Elena",
    pronunciation: "엘레나",
    gender: "female",
    meaning: "빛나는, 햇빛",
    elements: ["fire"],
    personality: "따뜻하고 매력적인",
    celebrity: "Elena Ferrante (소설가)",
  },
  {
    name: "Leo",
    pronunciation: "레오",
    gender: "male",
    meaning: "사자, 용맹한 리더",
    elements: ["fire"],
    personality: "카리스마 넘치는",
    celebrity: "Leonardo DiCaprio (배우)",
  },
  {
    name: "Aurora",
    pronunciation: "오로라",
    gender: "female",
    meaning: "새벽빛, 여명",
    elements: ["fire"],
    personality: "빛나고 희망적인",
    celebrity: "Aurora (노르웨이 가수)",
  },
  {
    name: "Phoenix",
    pronunciation: "피닉스",
    gender: "unisex",
    meaning: "불사조, 재탄생",
    elements: ["fire"],
    personality: "강렬하고 불굴의 의지를 가진",
    celebrity: "Joaquin Phoenix (배우)",
  },
  {
    name: "Stella",
    pronunciation: "스텔라",
    gender: "female",
    meaning: "별, 빛나는 존재",
    elements: ["fire", "water"],
    personality: "신비롭고 빛나는",
    celebrity: "Stella McCartney (디자이너)",
  },
  {
    name: "Ethan",
    pronunciation: "이든",
    gender: "male",
    meaning: "강한, 굳건한",
    elements: ["fire", "earth"],
    personality: "열정적이고 끈기 있는",
    celebrity: "Ethan Hawke (배우)",
  },

  // ─── 토(土) — 안정, 신뢰, 중심 ───
  {
    name: "Emma",
    pronunciation: "엠마",
    gender: "female",
    meaning: "전체적인, 보편적인",
    elements: ["earth"],
    personality: "포용력 있고 따뜻한",
    celebrity: "Emma Watson (배우)",
  },
  {
    name: "Adam",
    pronunciation: "아담",
    gender: "male",
    meaning: "땅, 최초의 인간",
    elements: ["earth"],
    personality: "근본적이고 성실한",
    celebrity: "Adam Driver (배우)",
  },
  {
    name: "Sophia",
    pronunciation: "소피아",
    gender: "female",
    meaning: "지혜, 현명함",
    elements: ["earth"],
    personality: "지적이고 차분한",
    celebrity: "Sophia Loren (배우)",
  },
  {
    name: "George",
    pronunciation: "조지",
    gender: "male",
    meaning: "농부, 대지를 다루는 자",
    elements: ["earth"],
    personality: "안정적이고 신뢰가 가는",
    celebrity: "George Clooney (배우)",
  },
  {
    name: "Terra",
    pronunciation: "테라",
    gender: "female",
    meaning: "대지, 지구",
    elements: ["earth"],
    personality: "든든하고 모성적인",
    celebrity: "Terra (게임 캐릭터, FF6)",
  },
  {
    name: "Noah",
    pronunciation: "노아",
    gender: "male",
    meaning: "안식, 평화",
    elements: ["earth", "water"],
    personality: "평화롭고 안정감 있는",
    celebrity: "Noah Centineo (배우)",
  },
  {
    name: "Grace",
    pronunciation: "그레이스",
    gender: "female",
    meaning: "우아함, 은총",
    elements: ["earth", "water"],
    personality: "우아하고 품격 있는",
    celebrity: "Grace Kelly (모나코 왕비)",
  },

  // ─── 금(金) — 결단력, 정의, 강인함 ───
  {
    name: "Alexander",
    pronunciation: "알렉산더",
    gender: "male",
    meaning: "인류의 수호자",
    elements: ["metal"],
    personality: "리더십이 강하고 정의로운",
    celebrity: "Alexander the Great (알렉산더 대왕)",
  },
  {
    name: "Victoria",
    pronunciation: "빅토리아",
    gender: "female",
    meaning: "승리",
    elements: ["metal"],
    personality: "당당하고 승리하는",
    celebrity: "Victoria Beckham (패션 디자이너)",
  },
  {
    name: "Ryan",
    pronunciation: "라이언",
    gender: "male",
    meaning: "작은 왕",
    elements: ["metal"],
    personality: "강인하고 당당한",
    celebrity: "Ryan Reynolds (배우)",
  },
  {
    name: "Diana",
    pronunciation: "다이애나",
    gender: "female",
    meaning: "신성한, 달의 여신",
    elements: ["metal", "water"],
    personality: "고결하고 카리스마 있는",
    celebrity: "Princess Diana (영국 왕세자비)",
  },
  {
    name: "Arthur",
    pronunciation: "아서",
    gender: "male",
    meaning: "곰처럼 강한, 고귀한",
    elements: ["metal"],
    personality: "고귀하고 용감한",
    celebrity: "King Arthur (아서왕 전설)",
  },
  {
    name: "Claire",
    pronunciation: "클레어",
    gender: "female",
    meaning: "밝은, 명확한",
    elements: ["metal", "fire"],
    personality: "명쾌하고 지적인",
    celebrity: "Claire Danes (배우)",
  },
  {
    name: "Marcus",
    pronunciation: "마커스",
    gender: "male",
    meaning: "전쟁의 신 마르스에서 유래",
    elements: ["metal", "fire"],
    personality: "용맹하고 결단력 있는",
    celebrity: "Marcus Aurelius (로마 황제)",
  },

  // ─── 수(水) — 지혜, 유연함, 통찰 ───
  {
    name: "Dylan",
    pronunciation: "딜런",
    gender: "male",
    meaning: "바다의 아들",
    elements: ["water"],
    personality: "자유롭고 직관적인",
    celebrity: "Bob Dylan (뮤지션)",
  },
  {
    name: "Marina",
    pronunciation: "마리나",
    gender: "female",
    meaning: "바다에서 온 사람",
    elements: ["water"],
    personality: "깊이 있고 신비로운",
    celebrity: "Marina Abramović (아티스트)",
  },
  {
    name: "Morgan",
    pronunciation: "모건",
    gender: "unisex",
    meaning: "바다의 수호자",
    elements: ["water"],
    personality: "지혜롭고 직관적인",
    celebrity: "Morgan Freeman (배우)",
  },
  {
    name: "Luna",
    pronunciation: "루나",
    gender: "female",
    meaning: "달, 밤의 빛",
    elements: ["water"],
    personality: "신비롭고 감성적인",
    celebrity: "Luna Lovegood (해리포터)",
  },
  {
    name: "Adrian",
    pronunciation: "에이드리언",
    gender: "male",
    meaning: "아드리아 해에서 온 사람",
    elements: ["water"],
    personality: "세련되고 깊이 있는",
    celebrity: "Adrian Grenier (배우)",
  },
  {
    name: "Chloe",
    pronunciation: "클로이",
    gender: "female",
    meaning: "푸른 새싹, 젊은 생명력",
    elements: ["water", "wood"],
    personality: "생기 넘치고 청춘의",
    celebrity: "Chloe Kim (스노보드 선수)",
  },
  {
    name: "Sean",
    pronunciation: "숀",
    gender: "male",
    meaning: "신의 은총",
    elements: ["water", "earth"],
    personality: "차분하고 신뢰감 있는",
    celebrity: "Sean Connery (배우)",
  },
  {
    name: "Mia",
    pronunciation: "미아",
    gender: "female",
    meaning: "나의 사랑, 소중한 사람",
    elements: ["water", "fire"],
    personality: "사랑스럽고 매력적인",
    celebrity: "Mia Farrow (배우)",
  },

  // ─── 추가 이름들 (다양한 오행 조합) ───
  {
    name: "Daniel",
    pronunciation: "다니엘",
    gender: "male",
    meaning: "신은 나의 심판자",
    elements: ["earth", "metal"],
    personality: "정의롭고 신뢰할 수 있는",
    celebrity: "Daniel Craig (배우)",
  },
  {
    name: "Emily",
    pronunciation: "에밀리",
    gender: "female",
    meaning: "부지런한, 열심히 노력하는",
    elements: ["earth", "fire"],
    personality: "성실하고 열정적인",
    celebrity: "Emily Blunt (배우)",
  },
  {
    name: "James",
    pronunciation: "제임스",
    gender: "male",
    meaning: "대체하는 자, 뒤따르는 자",
    elements: ["metal", "earth"],
    personality: "클래식하고 신사적인",
    celebrity: "James Dean (배우)",
  },
  {
    name: "Olivia",
    pronunciation: "올리비아",
    gender: "female",
    meaning: "올리브 나무, 평화",
    elements: ["wood", "earth"],
    personality: "조화롭고 평화로운",
    celebrity: "Olivia Rodrigo (가수)",
  },
  {
    name: "Henry",
    pronunciation: "헨리",
    gender: "male",
    meaning: "가정의 통치자",
    elements: ["earth", "metal"],
    personality: "책임감 있고 든든한",
    celebrity: "Henry Cavill (배우)",
  },
  {
    name: "Ava",
    pronunciation: "에이바",
    gender: "female",
    meaning: "생명, 숨결",
    elements: ["wood", "fire"],
    personality: "생동감 있고 활력 넘치는",
    celebrity: "Ava Gardner (배우)",
  },
  {
    name: "William",
    pronunciation: "윌리엄",
    gender: "male",
    meaning: "강한 의지의 수호자",
    elements: ["metal", "wood"],
    personality: "의지가 강하고 보호하는",
    celebrity: "Prince William (영국 왕세자)",
  },
  {
    name: "Charlotte",
    pronunciation: "샬롯",
    gender: "female",
    meaning: "자유로운 사람",
    elements: ["wood", "water"],
    personality: "자유롭고 우아한",
    celebrity: "Charlotte Brontë (작가)",
  },
  {
    name: "Benjamin",
    pronunciation: "벤자민",
    gender: "male",
    meaning: "오른손의 아들, 행운아",
    elements: ["water", "metal"],
    personality: "현명하고 행운이 따르는",
    celebrity: "Benjamin Franklin (정치인)",
  },
  {
    name: "Aria",
    pronunciation: "아리아",
    gender: "female",
    meaning: "노래, 멜로디",
    elements: ["fire", "water"],
    personality: "예술적이고 감각적인",
    celebrity: "Aria (오페라 용어)",
  },
];
