import type { Element } from "./saju";

export interface EnglishName {
  name: string;
  pronunciation: string;
  gender: "male" | "female" | "unisex";
  meaning: string;
  elements: Element[];
  personality: string;
  celebrity: string;
}

export const NAME_DB: EnglishName[] = [
  // ══════════════════════════════════
  //           남자 (125개)
  // ══════════════════════════════════

  // ── 목(木) 남자 25개 ──
  { name: "Oliver", pronunciation: "올리버", gender: "male", meaning: "올리브 나무, 평화의 상징", elements: ["wood"], personality: "자유롭고 창의적인", celebrity: "Oliver Stone (영화감독)" },
  { name: "Forest", pronunciation: "포레스트", gender: "male", meaning: "숲, 자연의 수호자", elements: ["wood"], personality: "깊이 있고 사려 깊은", celebrity: "Forest Whitaker (배우)" },
  { name: "Liam", pronunciation: "리암", gender: "male", meaning: "강한 의지의 전사", elements: ["wood", "metal"], personality: "용감하고 결단력 있는", celebrity: "Liam Neeson (배우)" },
  { name: "Logan", pronunciation: "로건", gender: "male", meaning: "작은 골짜기", elements: ["wood", "earth"], personality: "자유분방하고 독립적인", celebrity: "Hugh Jackman (로건 역)" },
  { name: "Asher", pronunciation: "애셔", gender: "male", meaning: "행복한, 축복받은", elements: ["wood"], personality: "밝고 긍정적인", celebrity: "Asher Angel (배우)" },
  { name: "Reed", pronunciation: "리드", gender: "male", meaning: "갈대, 유연한 힘", elements: ["wood", "water"], personality: "유연하고 적응력 있는", celebrity: "Reed Richards (마블 캐릭터)" },
  { name: "Cedric", pronunciation: "세드릭", gender: "male", meaning: "전투의 리더", elements: ["wood", "metal"], personality: "고결하고 정의로운", celebrity: "Cedric Diggory (해리포터)" },
  { name: "Rowan", pronunciation: "로완", gender: "male", meaning: "마가목, 보호의 나무", elements: ["wood"], personality: "보호적이고 따뜻한", celebrity: "Rowan Atkinson (배우)" },
  { name: "Silas", pronunciation: "사일러스", gender: "male", meaning: "숲의 사람", elements: ["wood", "earth"], personality: "묵직하고 신뢰감 있는", celebrity: "Silas Marner (소설 캐릭터)" },
  { name: "Jasper", pronunciation: "재스퍼", gender: "male", meaning: "보석, 자연의 선물", elements: ["wood", "earth"], personality: "차분하고 지적인", celebrity: "Jasper Johns (아티스트)" },
  { name: "Sylvan", pronunciation: "실반", gender: "male", meaning: "숲에 사는 사람", elements: ["wood"], personality: "자연과 하나 된", celebrity: "Sylvan Esso (뮤지션)" },
  { name: "Leif", pronunciation: "레이프", gender: "male", meaning: "후계자, 잎사귀", elements: ["wood"], personality: "모험적이고 개척하는", celebrity: "Leif Erikson (탐험가)" },
  { name: "Bryce", pronunciation: "브라이스", gender: "male", meaning: "빠른, 민첩한", elements: ["wood", "fire"], personality: "민첩하고 활기찬", celebrity: "Bryce Dallas Howard (배우)" },
  { name: "Heath", pronunciation: "히스", gender: "male", meaning: "황야, 들판", elements: ["wood", "earth"], personality: "자유로운 영혼의", celebrity: "Heath Ledger (배우)" },
  { name: "Orion", pronunciation: "오라이온", gender: "male", meaning: "사냥꾼 별자리", elements: ["wood", "fire"], personality: "모험적이고 빛나는", celebrity: "Orion (그리스 신화)" },
  { name: "Palmer", pronunciation: "팔머", gender: "male", meaning: "야자수를 가진 자", elements: ["wood"], personality: "여유롭고 평화로운", celebrity: "Arnold Palmer (골프선수)" },
  { name: "Alden", pronunciation: "올든", gender: "male", meaning: "오래된 친구", elements: ["wood", "earth"], personality: "믿음직하고 오래가는", celebrity: "Alden Ehrenreich (배우)" },
  { name: "Baxter", pronunciation: "백스터", gender: "male", meaning: "빵 굽는 사람", elements: ["wood", "fire"], personality: "따뜻하고 정성스러운", celebrity: "Baxter Dury (뮤지션)" },
  { name: "Vernon", pronunciation: "버논", gender: "male", meaning: "오리나무 숲", elements: ["wood"], personality: "강인하고 정직한", celebrity: "Vernon (세븐틴)" },
  { name: "Linden", pronunciation: "린든", gender: "male", meaning: "보리수나무", elements: ["wood", "water"], personality: "평온하고 치유하는", celebrity: "Lyndon B. Johnson (대통령)" },
  { name: "Burke", pronunciation: "버크", gender: "male", meaning: "요새에서 온 자", elements: ["wood", "metal"], personality: "단단하고 보호하는", celebrity: "Edmund Burke (정치가)" },
  { name: "Craig", pronunciation: "크레이그", gender: "male", meaning: "바위, 절벽", elements: ["wood", "earth"], personality: "굳건하고 안정적인", celebrity: "Daniel Craig (배우)" },
  { name: "Ellis", pronunciation: "엘리스", gender: "male", meaning: "자비로운", elements: ["wood", "water"], personality: "자비롭고 이해심 깊은", celebrity: "Ellis Island (이민역사)" },
  { name: "Gareth", pronunciation: "가레스", gender: "male", meaning: "온화한, 부드러운", elements: ["wood"], personality: "온화하고 부드러운", celebrity: "Gareth Bale (축구선수)" },
  { name: "Nolan", pronunciation: "놀런", gender: "male", meaning: "고귀한, 유명한", elements: ["wood", "metal"], personality: "고귀하고 명예로운", celebrity: "Christopher Nolan (감독)" },

  // ── 화(火) 남자 25개 ──
  { name: "Lucas", pronunciation: "루카스", gender: "male", meaning: "빛, 밝음을 가져오는 사람", elements: ["fire"], personality: "밝고 에너지 넘치는", celebrity: "George Lucas (영화감독)" },
  { name: "Leo", pronunciation: "레오", gender: "male", meaning: "사자, 용맹한 리더", elements: ["fire"], personality: "카리스마 넘치는", celebrity: "Leonardo DiCaprio (배우)" },
  { name: "Ethan", pronunciation: "이든", gender: "male", meaning: "강한, 굳건한", elements: ["fire", "earth"], personality: "열정적이고 끈기 있는", celebrity: "Ethan Hawke (배우)" },
  { name: "Aiden", pronunciation: "에이든", gender: "male", meaning: "불의 신, 작은 불꽃", elements: ["fire"], personality: "열정적이고 활동적인", celebrity: "Aiden Turner (배우)" },
  { name: "Blaze", pronunciation: "블레이즈", gender: "male", meaning: "불꽃, 타오르는 빛", elements: ["fire"], personality: "강렬하고 대담한", celebrity: "Blaze Bayley (뮤지션)" },
  { name: "Cyrus", pronunciation: "사이러스", gender: "male", meaning: "태양, 왕좌", elements: ["fire", "metal"], personality: "왕 같은 카리스마의", celebrity: "Cyrus the Great (페르시아 왕)" },
  { name: "Felix", pronunciation: "펠릭스", gender: "male", meaning: "행운의, 행복한", elements: ["fire", "wood"], personality: "행복하고 운 좋은", celebrity: "Felix Hernandez (야구선수)" },
  { name: "Hugo", pronunciation: "휴고", gender: "male", meaning: "영혼, 지성", elements: ["fire", "water"], personality: "지적이고 열정적인", celebrity: "Victor Hugo (작가)" },
  { name: "Ray", pronunciation: "레이", gender: "male", meaning: "빛줄기, 광선", elements: ["fire"], personality: "빛나고 따뜻한", celebrity: "Ray Charles (뮤지션)" },
  { name: "Kai", pronunciation: "카이", gender: "male", meaning: "바다, 불", elements: ["fire", "water"], personality: "자유롭고 열정적인", celebrity: "Kai (엑소 멤버)" },
  { name: "Ignatius", pronunciation: "이그나티우스", gender: "male", meaning: "불의, 열정적인", elements: ["fire"], personality: "뜨겁고 헌신적인", celebrity: "Ignatius of Loyola (성인)" },
  { name: "Kenji", pronunciation: "켄지", gender: "male", meaning: "건강한 둘째 아들", elements: ["fire", "earth"], personality: "건강하고 활력 넘치는", celebrity: "Kenji Mizoguchi (영화감독)" },
  { name: "Apollo", pronunciation: "아폴로", gender: "male", meaning: "태양의 신", elements: ["fire"], personality: "빛나고 예술적인", celebrity: "Apollo (그리스 신화)" },
  { name: "Dante", pronunciation: "단테", gender: "male", meaning: "지속하는, 인내하는", elements: ["fire", "earth"], personality: "인내심 강하고 깊은", celebrity: "Dante Alighieri (시인)" },
  { name: "Elio", pronunciation: "엘리오", gender: "male", meaning: "태양", elements: ["fire"], personality: "밝고 따뜻한", celebrity: "Elio (영화 콜미바이유어네임)" },
  { name: "Ashton", pronunciation: "애슈턴", gender: "male", meaning: "물푸레나무 마을", elements: ["fire", "wood"], personality: "활발하고 에너지 넘치는", celebrity: "Ashton Kutcher (배우)" },
  { name: "Ravi", pronunciation: "라비", gender: "male", meaning: "태양", elements: ["fire"], personality: "따뜻하고 빛나는", celebrity: "Ravi Shankar (음악가)" },
  { name: "Sol", pronunciation: "솔", gender: "male", meaning: "태양", elements: ["fire"], personality: "밝고 생명력 있는", celebrity: "Sol Campbell (축구선수)" },
  { name: "Lucian", pronunciation: "루시안", gender: "male", meaning: "빛의 사람", elements: ["fire", "water"], personality: "빛나고 지적인", celebrity: "Lucian Freud (화가)" },
  { name: "Hayden", pronunciation: "헤이든", gender: "male", meaning: "불의 골짜기", elements: ["fire", "earth"], personality: "열정과 안정의 조화", celebrity: "Hayden Christensen (배우)" },
  { name: "Kenneth", pronunciation: "케네스", gender: "male", meaning: "잘생긴, 불에서 태어난", elements: ["fire", "metal"], personality: "매력적이고 강인한", celebrity: "Kenneth Branagh (배우)" },
  { name: "Flynn", pronunciation: "플린", gender: "male", meaning: "붉은 머리의 아들", elements: ["fire"], personality: "밝고 쾌활한", celebrity: "Errol Flynn (배우)" },
  { name: "Jasiah", pronunciation: "제시아", gender: "male", meaning: "신이 치유하시다", elements: ["fire", "water"], personality: "치유하는 열정의", celebrity: "Jasiah (뮤지션)" },
  { name: "Nico", pronunciation: "니코", gender: "male", meaning: "승리의 사람", elements: ["fire", "metal"], personality: "승리하는 열정적인", celebrity: "Nico Rosberg (F1 드라이버)" },
  { name: "Theo", pronunciation: "테오", gender: "male", meaning: "신의 선물", elements: ["fire", "earth"], personality: "축복받은 따뜻한", celebrity: "Theo James (배우)" },

  // ── 토(土) 남자 25개 ──
  { name: "Adam", pronunciation: "아담", gender: "male", meaning: "땅, 최초의 인간", elements: ["earth"], personality: "근본적이고 성실한", celebrity: "Adam Driver (배우)" },
  { name: "George", pronunciation: "조지", gender: "male", meaning: "농부, 대지를 다루는 자", elements: ["earth"], personality: "안정적이고 신뢰가 가는", celebrity: "George Clooney (배우)" },
  { name: "Noah", pronunciation: "노아", gender: "male", meaning: "안식, 평화", elements: ["earth", "water"], personality: "평화롭고 안정감 있는", celebrity: "Noah Centineo (배우)" },
  { name: "Daniel", pronunciation: "다니엘", gender: "male", meaning: "신은 나의 심판자", elements: ["earth", "metal"], personality: "정의롭고 신뢰할 수 있는", celebrity: "Daniel Craig (배우)" },
  { name: "Henry", pronunciation: "헨리", gender: "male", meaning: "가정의 통치자", elements: ["earth", "metal"], personality: "책임감 있고 든든한", celebrity: "Henry Cavill (배우)" },
  { name: "Mason", pronunciation: "메이슨", gender: "male", meaning: "석공, 돌을 다루는 장인", elements: ["earth"], personality: "성실하고 꼼꼼한", celebrity: "Mason Mount (축구선수)" },
  { name: "Terrence", pronunciation: "테런스", gender: "male", meaning: "부드러운, 온화한", elements: ["earth"], personality: "온화하고 포용력 있는", celebrity: "Terrence Howard (배우)" },
  { name: "Clay", pronunciation: "클레이", gender: "male", meaning: "점토, 대지", elements: ["earth"], personality: "유연하면서 단단한", celebrity: "Clay Aiken (가수)" },
  { name: "Dustin", pronunciation: "더스틴", gender: "male", meaning: "용감한 전사의 돌", elements: ["earth", "metal"], personality: "강인하고 끈기 있는", celebrity: "Dustin Hoffman (배우)" },
  { name: "Grant", pronunciation: "그랜트", gender: "male", meaning: "위대한, 큰", elements: ["earth", "fire"], personality: "대범하고 관대한", celebrity: "Cary Grant (배우)" },
  { name: "Clayton", pronunciation: "클레이턴", gender: "male", meaning: "점토 마을", elements: ["earth"], personality: "안정적이고 충실한", celebrity: "Clayton Kershaw (야구선수)" },
  { name: "Miles", pronunciation: "마일스", gender: "male", meaning: "자비로운, 군인", elements: ["earth", "metal"], personality: "자비롭고 강인한", celebrity: "Miles Davis (재즈 뮤지션)" },
  { name: "Landon", pronunciation: "랜던", gender: "male", meaning: "긴 언덕", elements: ["earth"], personality: "든든하고 지속적인", celebrity: "Landon Donovan (축구선수)" },
  { name: "Trent", pronunciation: "트렌트", gender: "male", meaning: "강을 건너는 자", elements: ["earth", "water"], personality: "균형 잡히고 안정적인", celebrity: "Trent Alexander-Arnold (축구선수)" },
  { name: "Seth", pronunciation: "세스", gender: "male", meaning: "지정된, 임명된", elements: ["earth"], personality: "운명적이고 확고한", celebrity: "Seth Rogen (배우)" },
  { name: "Caleb", pronunciation: "케일럽", gender: "male", meaning: "충실한, 헌신적인", elements: ["earth", "water"], personality: "충실하고 헌신적인", celebrity: "Caleb Followill (뮤지션)" },
  { name: "Gavin", pronunciation: "개빈", gender: "male", meaning: "흰 매", elements: ["earth", "metal"], personality: "고귀하고 날카로운", celebrity: "Gavin Rossdale (뮤지션)" },
  { name: "Derek", pronunciation: "데릭", gender: "male", meaning: "통치자, 리더", elements: ["earth", "fire"], personality: "이끄는 힘이 있는", celebrity: "Derek Jeter (야구선수)" },
  { name: "Warren", pronunciation: "워렌", gender: "male", meaning: "수호자, 보호자", elements: ["earth"], personality: "보호하고 지키는", celebrity: "Warren Buffett (투자가)" },
  { name: "Perry", pronunciation: "페리", gender: "male", meaning: "배나무", elements: ["earth", "wood"], personality: "풍요롭고 열매 맺는", celebrity: "Katy Perry (가수)" },
  { name: "Lance", pronunciation: "랜스", gender: "male", meaning: "창, 땅", elements: ["earth", "metal"], personality: "날카롭고 정확한", celebrity: "Lance Armstrong (사이클선수)" },
  { name: "Brock", pronunciation: "브록", gender: "male", meaning: "오소리, 바위", elements: ["earth"], personality: "강인하고 끈질긴", celebrity: "Brock Lesnar (레슬러)" },
  { name: "Travis", pronunciation: "트래비스", gender: "male", meaning: "길을 건너는 자", elements: ["earth", "wood"], personality: "모험적이면서 안정적인", celebrity: "Travis Scott (뮤지션)" },
  { name: "Glenn", pronunciation: "글렌", gender: "male", meaning: "좁은 골짜기", elements: ["earth", "water"], personality: "깊이 있고 평온한", celebrity: "Glenn Close (배우)" },
  { name: "Phillip", pronunciation: "필립", gender: "male", meaning: "말을 사랑하는 자", elements: ["earth", "fire"], personality: "열정적이고 충직한", celebrity: "Prince Philip (영국 왕배)" },

  // ── 금(金) 남자 25개 ──
  { name: "Alexander", pronunciation: "알렉산더", gender: "male", meaning: "인류의 수호자", elements: ["metal"], personality: "리더십이 강하고 정의로운", celebrity: "Alexander the Great (대왕)" },
  { name: "Ryan", pronunciation: "라이언", gender: "male", meaning: "작은 왕", elements: ["metal"], personality: "강인하고 당당한", celebrity: "Ryan Reynolds (배우)" },
  { name: "Arthur", pronunciation: "아서", gender: "male", meaning: "곰처럼 강한, 고귀한", elements: ["metal"], personality: "고귀하고 용감한", celebrity: "King Arthur (아서왕 전설)" },
  { name: "James", pronunciation: "제임스", gender: "male", meaning: "대체하는 자", elements: ["metal", "earth"], personality: "클래식하고 신사적인", celebrity: "James Dean (배우)" },
  { name: "William", pronunciation: "윌리엄", gender: "male", meaning: "강한 의지의 수호자", elements: ["metal", "wood"], personality: "의지가 강하고 보호하는", celebrity: "Prince William (영국 왕세자)" },
  { name: "Marcus", pronunciation: "마커스", gender: "male", meaning: "전쟁의 신에서 유래", elements: ["metal", "fire"], personality: "용맹하고 결단력 있는", celebrity: "Marcus Aurelius (로마 황제)" },
  { name: "Oscar", pronunciation: "오스카", gender: "male", meaning: "신의 창, 전사", elements: ["metal"], personality: "날카롭고 지적인", celebrity: "Oscar Wilde (작가)" },
  { name: "Victor", pronunciation: "빅터", gender: "male", meaning: "승리자", elements: ["metal", "fire"], personality: "승리하는, 강인한", celebrity: "Victor Hugo (작가)" },
  { name: "Sterling", pronunciation: "스털링", gender: "male", meaning: "순수한 은, 가치 있는", elements: ["metal"], personality: "고귀하고 가치 있는", celebrity: "Sterling K. Brown (배우)" },
  { name: "Carl", pronunciation: "칼", gender: "male", meaning: "자유로운 남자", elements: ["metal", "wood"], personality: "자유롭고 강단 있는", celebrity: "Carl Sagan (천문학자)" },
  { name: "Maxwell", pronunciation: "맥스웰", gender: "male", meaning: "위대한 샘", elements: ["metal", "water"], personality: "강하고 풍요로운", celebrity: "Maxwell (뮤지션)" },
  { name: "Dominic", pronunciation: "도미닉", gender: "male", meaning: "주님의", elements: ["metal"], personality: "권위 있고 당당한", celebrity: "Dominic Toretto (분노의 질주)" },
  { name: "Tristan", pronunciation: "트리스탄", gender: "male", meaning: "소란, 용감한 기사", elements: ["metal", "fire"], personality: "용감하고 로맨틱한", celebrity: "Tristan (아서왕 전설)" },
  { name: "Axel", pronunciation: "악셀", gender: "male", meaning: "평화의 아버지", elements: ["metal"], personality: "강인하면서 평화를 추구하는", celebrity: "Axl Rose (뮤지션)" },
  { name: "Conrad", pronunciation: "콘래드", gender: "male", meaning: "용감한 조언자", elements: ["metal", "earth"], personality: "지혜롭고 용감한", celebrity: "Joseph Conrad (작가)" },
  { name: "Roland", pronunciation: "롤랜드", gender: "male", meaning: "유명한 땅", elements: ["metal", "earth"], personality: "명예롭고 강한", celebrity: "Roland (프랑스 전설)" },
  { name: "Pierce", pronunciation: "피어스", gender: "male", meaning: "바위, 돌", elements: ["metal"], personality: "관통하는 날카로운", celebrity: "Pierce Brosnan (배우)" },
  { name: "Rex", pronunciation: "렉스", gender: "male", meaning: "왕", elements: ["metal", "fire"], personality: "왕 같은 위엄의", celebrity: "Rex Harrison (배우)" },
  { name: "Jasper", pronunciation: "재스퍼", gender: "male", meaning: "보석을 가진 자", elements: ["metal", "earth"], personality: "가치 있고 빛나는", celebrity: "Jasper (트와일라잇)" },
  { name: "Griffin", pronunciation: "그리핀", gender: "male", meaning: "강한 군주", elements: ["metal", "wood"], personality: "강하고 신화적인", celebrity: "Griffin (신화 생물)" },
  { name: "Lance", pronunciation: "랜스", gender: "male", meaning: "창, 무기", elements: ["metal"], personality: "날카롭고 정확한", celebrity: "Lance Armstrong (사이클선수)" },
  { name: "Everett", pronunciation: "에버렛", gender: "male", meaning: "멧돼지처럼 강한", elements: ["metal", "wood"], personality: "강인하고 지속적인", celebrity: "Everett (영화)" },
  { name: "Hector", pronunciation: "헥터", gender: "male", meaning: "지키는 자", elements: ["metal"], personality: "보호하고 지키는", celebrity: "Hector (트로이 전쟁)" },
  { name: "Ivan", pronunciation: "이반", gender: "male", meaning: "신의 은총", elements: ["metal", "water"], personality: "은혜롭고 강한", celebrity: "Ivan the Great (러시아 대제)" },
  { name: "Garrett", pronunciation: "개럿", gender: "male", meaning: "창으로 다스리는 자", elements: ["metal"], personality: "통솔력 있고 정의로운", celebrity: "Garrett Hedlund (배우)" },

  // ── 수(水) 남자 25개 ──
  { name: "Dylan", pronunciation: "딜런", gender: "male", meaning: "바다의 아들", elements: ["water"], personality: "자유롭고 직관적인", celebrity: "Bob Dylan (뮤지션)" },
  { name: "Adrian", pronunciation: "에이드리언", gender: "male", meaning: "아드리아 해에서 온 사람", elements: ["water"], personality: "세련되고 깊이 있는", celebrity: "Adrian Grenier (배우)" },
  { name: "Sean", pronunciation: "숀", gender: "male", meaning: "신의 은총", elements: ["water", "earth"], personality: "차분하고 신뢰감 있는", celebrity: "Sean Connery (배우)" },
  { name: "Benjamin", pronunciation: "벤자민", gender: "male", meaning: "오른손의 아들, 행운아", elements: ["water", "metal"], personality: "현명하고 행운이 따르는", celebrity: "Benjamin Franklin (정치인)" },
  { name: "Brooks", pronunciation: "브룩스", gender: "male", meaning: "시냇물", elements: ["water"], personality: "맑고 순수한", celebrity: "Brooks Robinson (야구선수)" },
  { name: "Irving", pronunciation: "어빙", gender: "male", meaning: "바다의 친구", elements: ["water"], personality: "깊이 있고 사교적인", celebrity: "Irving Berlin (작곡가)" },
  { name: "Nile", pronunciation: "나일", gender: "male", meaning: "나일강, 생명의 강", elements: ["water"], personality: "풍요롭고 생명력 있는", celebrity: "Nile Rodgers (뮤지션)" },
  { name: "Caspian", pronunciation: "카스피안", gender: "male", meaning: "카스피해", elements: ["water", "earth"], personality: "광대하고 모험적인", celebrity: "Prince Caspian (나니아 연대기)" },
  { name: "Kendrick", pronunciation: "켄드릭", gender: "male", meaning: "왕의 힘", elements: ["water", "metal"], personality: "지혜롭고 강력한", celebrity: "Kendrick Lamar (래퍼)" },
  { name: "Douglas", pronunciation: "더글라스", gender: "male", meaning: "어두운 물", elements: ["water", "wood"], personality: "깊고 신비로운", celebrity: "Douglas Adams (작가)" },
  { name: "Murphy", pronunciation: "머피", gender: "male", meaning: "바다의 전사", elements: ["water", "metal"], personality: "용감하고 깊이 있는", celebrity: "Eddie Murphy (배우)" },
  { name: "Neptune", pronunciation: "넵튠", gender: "male", meaning: "바다의 신", elements: ["water"], personality: "신비롭고 깊이 있는", celebrity: "Neptune (로마 신화)" },
  { name: "Finn", pronunciation: "핀", gender: "male", meaning: "공정한, 흰", elements: ["water", "metal"], personality: "공정하고 맑은", celebrity: "Finn Wolfhard (배우)" },
  { name: "Wade", pronunciation: "웨이드", gender: "male", meaning: "강을 건너는 자", elements: ["water"], personality: "용감하고 개척하는", celebrity: "Dwayne Wade (농구선수)" },
  { name: "Lake", pronunciation: "레이크", gender: "male", meaning: "호수", elements: ["water"], personality: "고요하고 깊은", celebrity: "Lake Bell (배우)" },
  { name: "Clifford", pronunciation: "클리포드", gender: "male", meaning: "절벽 옆 여울", elements: ["water", "earth"], personality: "강인하고 맑은", celebrity: "Clifford (애니메이션)" },
  { name: "Murray", pronunciation: "머레이", gender: "male", meaning: "바다의 정착지", elements: ["water"], personality: "안정적이고 깊이 있는", celebrity: "Bill Murray (배우)" },
  { name: "Dorian", pronunciation: "도리안", gender: "male", meaning: "바다에서 온 자", elements: ["water", "fire"], personality: "신비롭고 매력적인", celebrity: "Dorian Gray (소설 캐릭터)" },
  { name: "Kelvin", pronunciation: "켈빈", gender: "male", meaning: "좁은 강", elements: ["water"], personality: "지적이고 정확한", celebrity: "Lord Kelvin (물리학자)" },
  { name: "Merlin", pronunciation: "멀린", gender: "male", meaning: "바다의 요새", elements: ["water", "metal"], personality: "마법같이 지혜로운", celebrity: "Merlin (아서왕 전설)" },
  { name: "Beckett", pronunciation: "베켓", gender: "male", meaning: "시냇물 근처", elements: ["water", "wood"], personality: "자연스럽고 예술적인", celebrity: "Samuel Beckett (극작가)" },
  { name: "River", pronunciation: "리버", gender: "male", meaning: "강", elements: ["water"], personality: "흐르듯 자유로운", celebrity: "River Phoenix (배우)" },
  { name: "Marshall", pronunciation: "마샬", gender: "male", meaning: "말을 관리하는 자", elements: ["water", "earth"], personality: "질서 있고 리더십 있는", celebrity: "Marshall Mathers (에미넘)" },
  { name: "Monroe", pronunciation: "먼로", gender: "male", meaning: "강 어귀", elements: ["water"], personality: "매력적이고 인상적인", celebrity: "James Monroe (대통령)" },
  { name: "Tate", pronunciation: "테이트", gender: "male", meaning: "쾌활한", elements: ["water", "fire"], personality: "쾌활하고 밝은", celebrity: "Tate Modern (미술관)" },

  // ══════════════════════════════════
  //           여자 (125개)
  // ══════════════════════════════════

  // ── 목(木) 여자 25개 ──
  { name: "Sylvia", pronunciation: "실비아", gender: "female", meaning: "숲, 자연에서 온 사람", elements: ["wood"], personality: "자연을 사랑하는 감성적인", celebrity: "Sylvia Plath (시인)" },
  { name: "Ashley", pronunciation: "애슐리", gender: "female", meaning: "물푸레나무 숲", elements: ["wood"], personality: "밝고 생기 넘치는", celebrity: "Ashley Graham (모델)" },
  { name: "Ivy", pronunciation: "아이비", gender: "female", meaning: "담쟁이, 끈기와 성장", elements: ["wood"], personality: "강인하고 끈기 있는", celebrity: "Beyoncé의 딸 Blue Ivy" },
  { name: "Hazel", pronunciation: "헤이즐", gender: "female", meaning: "개암나무, 지혜", elements: ["wood", "earth"], personality: "따뜻하고 지혜로운", celebrity: "Hazel Scott (재즈 피아니스트)" },
  { name: "Olivia", pronunciation: "올리비아", gender: "female", meaning: "올리브 나무, 평화", elements: ["wood", "earth"], personality: "조화롭고 평화로운", celebrity: "Olivia Rodrigo (가수)" },
  { name: "Ava", pronunciation: "에이바", gender: "female", meaning: "생명, 숨결", elements: ["wood", "fire"], personality: "생동감 있고 활력 넘치는", celebrity: "Ava Gardner (배우)" },
  { name: "Charlotte", pronunciation: "샬롯", gender: "female", meaning: "자유로운 사람", elements: ["wood", "water"], personality: "자유롭고 우아한", celebrity: "Charlotte Brontë (작가)" },
  { name: "Willow", pronunciation: "윌로우", gender: "female", meaning: "버드나무, 유연한 아름다움", elements: ["wood", "water"], personality: "유연하고 우아한", celebrity: "Willow Smith (가수)" },
  { name: "Laurel", pronunciation: "로렐", gender: "female", meaning: "월계수, 승리의 관", elements: ["wood", "metal"], personality: "승리하는, 고귀한", celebrity: "Laurel (코미디 듀오)" },
  { name: "Fern", pronunciation: "펀", gender: "female", meaning: "양치식물, 진실함", elements: ["wood"], personality: "순수하고 진실된", celebrity: "Fern (영화 노매드랜드)" },
  { name: "Magnolia", pronunciation: "매그놀리아", gender: "female", meaning: "목련, 고귀한 아름다움", elements: ["wood"], personality: "고귀하고 아름다운", celebrity: "Magnolia (영화)" },
  { name: "Flora", pronunciation: "플로라", gender: "female", meaning: "꽃의 여신", elements: ["wood", "fire"], personality: "꽃처럼 화사한", celebrity: "Flora (로마 신화)" },
  { name: "Dahlia", pronunciation: "달리아", gender: "female", meaning: "꽃 이름, 우아함", elements: ["wood"], personality: "우아하고 기품 있는", celebrity: "Black Dahlia (영화)" },
  { name: "Iris", pronunciation: "아이리스", gender: "female", meaning: "무지개, 전령의 여신", elements: ["wood", "water"], personality: "다채롭고 희망적인", celebrity: "Iris Apfel (패션 아이콘)" },
  { name: "Sage", pronunciation: "세이지", gender: "female", meaning: "현명한, 허브", elements: ["wood", "earth"], personality: "현명하고 자연적인", celebrity: "Sage (허브)" },
  { name: "Violet", pronunciation: "바이올렛", gender: "female", meaning: "제비꽃, 보라색", elements: ["wood", "water"], personality: "수줍고 아름다운", celebrity: "Violet Crawley (다운튼 애비)" },
  { name: "Heather", pronunciation: "헤더", gender: "female", meaning: "히스꽃, 들판", elements: ["wood"], personality: "자연스럽고 순수한", celebrity: "Heather Graham (배우)" },
  { name: "Rosemary", pronunciation: "로즈마리", gender: "female", meaning: "바다의 이슬, 기억의 허브", elements: ["wood", "water"], personality: "기억에 남는 향기로운", celebrity: "Rosemary Clooney (가수)" },
  { name: "Autumn", pronunciation: "오텀", gender: "female", meaning: "가을, 풍요의 계절", elements: ["wood", "earth"], personality: "풍요롭고 성숙한", celebrity: "Autumn Phillips (영국 왕실)" },
  { name: "Elise", pronunciation: "엘리스", gender: "female", meaning: "신에게 바쳐진", elements: ["wood", "fire"], personality: "순수하고 헌신적인", celebrity: "Für Elise (베토벤)" },
  { name: "Liana", pronunciation: "리아나", gender: "female", meaning: "덩굴, 연결하는 자", elements: ["wood"], personality: "연결하고 이어주는", celebrity: "Liana Liberato (배우)" },
  { name: "Jasmine", pronunciation: "재스민", gender: "female", meaning: "재스민 꽃, 향기", elements: ["wood", "fire"], personality: "향기롭고 매혹적인", celebrity: "Princess Jasmine (알라딘)" },
  { name: "Holly", pronunciation: "홀리", gender: "female", meaning: "호랑가시나무", elements: ["wood", "metal"], personality: "날카롭고 보호적인", celebrity: "Holly Hunter (배우)" },
  { name: "Briar", pronunciation: "브라이어", gender: "female", meaning: "가시나무, 야생의", elements: ["wood"], personality: "야생적이고 강인한", celebrity: "Briar Rose (잠자는 숲속 공주)" },
  { name: "Maple", pronunciation: "메이플", gender: "female", meaning: "단풍나무", elements: ["wood", "fire"], personality: "아름답게 변화하는", celebrity: "Maple (자연)" },

  // ── 화(火) 여자 25개 ──
  { name: "Elena", pronunciation: "엘레나", gender: "female", meaning: "빛나는, 햇빛", elements: ["fire"], personality: "따뜻하고 매력적인", celebrity: "Elena Ferrante (소설가)" },
  { name: "Aurora", pronunciation: "오로라", gender: "female", meaning: "새벽빛, 여명", elements: ["fire"], personality: "빛나고 희망적인", celebrity: "Aurora (노르웨이 가수)" },
  { name: "Stella", pronunciation: "스텔라", gender: "female", meaning: "별, 빛나는 존재", elements: ["fire", "water"], personality: "신비롭고 빛나는", celebrity: "Stella McCartney (디자이너)" },
  { name: "Aria", pronunciation: "아리아", gender: "female", meaning: "노래, 멜로디", elements: ["fire", "water"], personality: "예술적이고 감각적인", celebrity: "Aria (오페라 용어)" },
  { name: "Emily", pronunciation: "에밀리", gender: "female", meaning: "부지런한, 열심히 노력하는", elements: ["fire", "earth"], personality: "성실하고 열정적인", celebrity: "Emily Blunt (배우)" },
  { name: "Scarlett", pronunciation: "스칼렛", gender: "female", meaning: "붉은색, 강렬한", elements: ["fire"], personality: "강렬하고 매혹적인", celebrity: "Scarlett Johansson (배우)" },
  { name: "Ruby", pronunciation: "루비", gender: "female", meaning: "루비, 붉은 보석", elements: ["fire", "metal"], personality: "열정적이고 귀한", celebrity: "Ruby Rose (배우)" },
  { name: "Elara", pronunciation: "엘라라", gender: "female", meaning: "빛나는 별", elements: ["fire"], personality: "빛나고 강인한", celebrity: "Elara (목성의 위성)" },
  { name: "Sunny", pronunciation: "서니", gender: "female", meaning: "햇살, 밝은", elements: ["fire", "wood"], personality: "밝고 에너지 넘치는", celebrity: "Sunny (소녀시대)" },
  { name: "Nora", pronunciation: "노라", gender: "female", meaning: "빛, 명예", elements: ["fire", "earth"], personality: "명예롭고 따뜻한", celebrity: "Nora Jones (뮤지션)" },
  { name: "Seraphina", pronunciation: "세라피나", gender: "female", meaning: "불꽃의 천사", elements: ["fire"], personality: "천사같이 빛나는", celebrity: "Seraphina Affleck (유명인 자녀)" },
  { name: "Phoebe", pronunciation: "피비", gender: "female", meaning: "빛나는, 밝은", elements: ["fire", "water"], personality: "밝고 유쾌한", celebrity: "Phoebe Waller-Bridge (배우)" },
  { name: "Ember", pronunciation: "엠버", gender: "female", meaning: "불씨, 잔불", elements: ["fire"], personality: "은은하지만 강렬한", celebrity: "Amber (가수)" },
  { name: "Dawn", pronunciation: "던", gender: "female", meaning: "새벽, 시작", elements: ["fire", "wood"], personality: "새로운 시작의", celebrity: "Dawn French (배우)" },
  { name: "Candace", pronunciation: "캔디스", gender: "female", meaning: "빛나는, 순수한 흰색", elements: ["fire"], personality: "순수하고 빛나는", celebrity: "Candace Cameron (배우)" },
  { name: "Sienna", pronunciation: "시에나", gender: "female", meaning: "따뜻한 갈색, 대지의 색", elements: ["fire", "earth"], personality: "따뜻하고 열정적인", celebrity: "Sienna Miller (배우)" },
  { name: "Blaire", pronunciation: "블레어", gender: "female", meaning: "들판, 전장", elements: ["fire", "metal"], personality: "강렬하고 전략적인", celebrity: "Blair Waldorf (가십걸)" },
  { name: "Lucia", pronunciation: "루시아", gender: "female", meaning: "빛", elements: ["fire"], personality: "빛처럼 밝은", celebrity: "Lucia di Lammermoor (오페라)" },
  { name: "Celeste", pronunciation: "셀레스트", gender: "female", meaning: "하늘의, 천상의", elements: ["fire", "water"], personality: "천상의 아름다움을 가진", celebrity: "Celeste (가수)" },
  { name: "Helena", pronunciation: "헬레나", gender: "female", meaning: "빛나는 횃불", elements: ["fire"], personality: "열렬하고 빛나는", celebrity: "Helena Bonham Carter (배우)" },
  { name: "Ayla", pronunciation: "아일라", gender: "female", meaning: "달빛, 후광", elements: ["fire", "water"], personality: "신비롭고 빛나는", celebrity: "Ayla (소설 캐릭터)" },
  { name: "Summer", pronunciation: "서머", gender: "female", meaning: "여름, 따뜻한 계절", elements: ["fire", "wood"], personality: "따뜻하고 활기찬", celebrity: "Summer Glau (배우)" },
  { name: "Thea", pronunciation: "테아", gender: "female", meaning: "여신, 신성한", elements: ["fire", "earth"], personality: "신성하고 고귀한", celebrity: "Thea Queen (애로우)" },
  { name: "Roxanne", pronunciation: "록산", gender: "female", meaning: "새벽빛, 밝은 별", elements: ["fire"], personality: "새벽같이 빛나는", celebrity: "Roxanne (노래)" },
  { name: "Lyra", pronunciation: "라이라", gender: "female", meaning: "거문고자리, 음악", elements: ["fire", "metal"], personality: "음악적이고 조화로운", celebrity: "Lyra (황금나침반)" },

  // ── 토(土) 여자 25개 ──
  { name: "Emma", pronunciation: "엠마", gender: "female", meaning: "전체적인, 보편적인", elements: ["earth"], personality: "포용력 있고 따뜻한", celebrity: "Emma Watson (배우)" },
  { name: "Sophia", pronunciation: "소피아", gender: "female", meaning: "지혜, 현명함", elements: ["earth"], personality: "지적이고 차분한", celebrity: "Sophia Loren (배우)" },
  { name: "Terra", pronunciation: "테라", gender: "female", meaning: "대지, 지구", elements: ["earth"], personality: "든든하고 모성적인", celebrity: "Terra (게임 캐릭터, FF6)" },
  { name: "Grace", pronunciation: "그레이스", gender: "female", meaning: "우아함, 은총", elements: ["earth", "water"], personality: "우아하고 품격 있는", celebrity: "Grace Kelly (모나코 왕비)" },
  { name: "Hannah", pronunciation: "한나", gender: "female", meaning: "은총, 자비", elements: ["earth"], personality: "자비롭고 따뜻한", celebrity: "Hannah Arendt (철학자)" },
  { name: "Maya", pronunciation: "마야", gender: "female", meaning: "환상, 대지의 어머니", elements: ["earth", "water"], personality: "신비롭고 모성적인", celebrity: "Maya Angelou (시인)" },
  { name: "Gaia", pronunciation: "가이아", gender: "female", meaning: "대지의 여신", elements: ["earth"], personality: "모든 것을 품는 따뜻한", celebrity: "Gaia (그리스 신화)" },
  { name: "Jade", pronunciation: "제이드", gender: "female", meaning: "옥, 고귀한 보석", elements: ["earth", "metal"], personality: "고귀하고 단단한", celebrity: "Jade Thirlwall (리틀믹스)" },
  { name: "Petra", pronunciation: "페트라", gender: "female", meaning: "바위, 굳건한", elements: ["earth", "metal"], personality: "강인하고 변치 않는", celebrity: "Petra (요르단 고대 도시)" },
  { name: "Abigail", pronunciation: "아비게일", gender: "female", meaning: "아버지의 기쁨", elements: ["earth"], personality: "기쁨을 주는 따뜻한", celebrity: "Abigail Adams (영부인)" },
  { name: "Clara", pronunciation: "클라라", gender: "female", meaning: "밝은, 명확한", elements: ["earth", "fire"], personality: "명확하고 지적인", celebrity: "Clara Schumann (피아니스트)" },
  { name: "Ruth", pronunciation: "루스", gender: "female", meaning: "친구, 동반자", elements: ["earth"], personality: "충실하고 헌신적인", celebrity: "Ruth Bader Ginsburg (대법관)" },
  { name: "Martha", pronunciation: "마사", gender: "female", meaning: "여주인, 관리하는 자", elements: ["earth", "metal"], personality: "관리력 있고 실용적인", celebrity: "Martha Stewart (사업가)" },
  { name: "Leah", pronunciation: "레아", gender: "female", meaning: "지친, 자연의", elements: ["earth", "wood"], personality: "자연스럽고 인내하는", celebrity: "Leah (성경 인물)" },
  { name: "Naomi", pronunciation: "나오미", gender: "female", meaning: "즐거운, 아름다운", elements: ["earth", "fire"], personality: "즐겁고 아름다운", celebrity: "Naomi Campbell (모델)" },
  { name: "Adelaide", pronunciation: "애들레이드", gender: "female", meaning: "고귀한 성품", elements: ["earth"], personality: "고귀하고 품격 있는", celebrity: "Adelaide (호주 도시)" },
  { name: "Gemma", pronunciation: "젬마", gender: "female", meaning: "보석", elements: ["earth", "metal"], personality: "빛나고 가치 있는", celebrity: "Gemma Chan (배우)" },
  { name: "Maisie", pronunciation: "메이지", gender: "female", meaning: "진주, 빛의 아이", elements: ["earth", "water"], personality: "맑고 빛나는", celebrity: "Maisie Williams (배우)" },
  { name: "Bethany", pronunciation: "베서니", gender: "female", meaning: "무화과의 집", elements: ["earth", "wood"], personality: "풍요롭고 따뜻한", celebrity: "Bethany Hamilton (서퍼)" },
  { name: "Cora", pronunciation: "코라", gender: "female", meaning: "소녀, 처녀", elements: ["earth"], personality: "순수하고 단아한", celebrity: "Cora (다운튼 애비)" },
  { name: "Millie", pronunciation: "밀리", gender: "female", meaning: "부지런한, 강한", elements: ["earth", "fire"], personality: "부지런하고 활기찬", celebrity: "Millie Bobby Brown (배우)" },
  { name: "Eloise", pronunciation: "엘로이즈", gender: "female", meaning: "건강한, 넓은", elements: ["earth", "wood"], personality: "건강하고 넓은 마음의", celebrity: "Eloise (아동 소설)" },
  { name: "Margot", pronunciation: "마고", gender: "female", meaning: "진주", elements: ["earth", "water"], personality: "빛나고 우아한", celebrity: "Margot Robbie (배우)" },
  { name: "Tessa", pronunciation: "테사", gender: "female", meaning: "수확하는 사람", elements: ["earth"], personality: "열매를 맺는 성실한", celebrity: "Tessa Thompson (배우)" },
  { name: "Wren", pronunciation: "렌", gender: "female", meaning: "굴뚝새, 작지만 강한", elements: ["earth", "wood"], personality: "작지만 강인한", celebrity: "Wren (새)" },

  // ── 금(金) 여자 25개 ──
  { name: "Victoria", pronunciation: "빅토리아", gender: "female", meaning: "승리", elements: ["metal"], personality: "당당하고 승리하는", celebrity: "Victoria Beckham (디자이너)" },
  { name: "Diana", pronunciation: "다이애나", gender: "female", meaning: "신성한, 달의 여신", elements: ["metal", "water"], personality: "고결하고 카리스마 있는", celebrity: "Princess Diana (왕세자비)" },
  { name: "Claire", pronunciation: "클레어", gender: "female", meaning: "밝은, 명확한", elements: ["metal", "fire"], personality: "명쾌하고 지적인", celebrity: "Claire Danes (배우)" },
  { name: "Audrey", pronunciation: "오드리", gender: "female", meaning: "고귀한 힘", elements: ["metal"], personality: "우아하고 고귀한", celebrity: "Audrey Hepburn (배우)" },
  { name: "Athena", pronunciation: "아테나", gender: "female", meaning: "지혜의 여신", elements: ["metal", "earth"], personality: "지혜롭고 전략적인", celebrity: "Athena (그리스 신화)" },
  { name: "Regina", pronunciation: "레지나", gender: "female", meaning: "여왕", elements: ["metal"], personality: "왕 같은 리더십의", celebrity: "Regina King (배우)" },
  { name: "Brielle", pronunciation: "브리엘", gender: "female", meaning: "신은 나의 힘", elements: ["metal", "fire"], personality: "강인하고 신성한", celebrity: "Brielle (가수)" },
  { name: "Freya", pronunciation: "프레이아", gender: "female", meaning: "사랑과 전쟁의 여신", elements: ["metal", "fire"], personality: "강렬하고 아름다운", celebrity: "Freya (노르드 신화)" },
  { name: "Ingrid", pronunciation: "잉그리드", gender: "female", meaning: "아름다운 신", elements: ["metal", "water"], personality: "신비롭고 아름다운", celebrity: "Ingrid Bergman (배우)" },
  { name: "Zelda", pronunciation: "젤다", gender: "female", meaning: "행복한 전사", elements: ["metal", "wood"], personality: "용감하고 행복한", celebrity: "Zelda (게임 캐릭터)" },
  { name: "Valerie", pronunciation: "발레리", gender: "female", meaning: "강한, 용감한", elements: ["metal"], personality: "용감하고 강인한", celebrity: "Valerie (노래)" },
  { name: "Cassandra", pronunciation: "카산드라", gender: "female", meaning: "예언하는 자", elements: ["metal", "water"], personality: "직관적이고 예리한", celebrity: "Cassandra (그리스 신화)" },
  { name: "Gwendolyn", pronunciation: "그웬돌린", gender: "female", meaning: "하얀 원, 축복받은", elements: ["metal"], personality: "축복받고 순수한", celebrity: "Gwen Stacy (스파이더맨)" },
  { name: "Minerva", pronunciation: "미네르바", gender: "female", meaning: "지혜의 여신", elements: ["metal", "earth"], personality: "지혜롭고 전략적인", celebrity: "Minerva McGonagall (해리포터)" },
  { name: "Beatrice", pronunciation: "베아트리체", gender: "female", meaning: "축복을 가져오는 자", elements: ["metal", "fire"], personality: "축복하고 밝히는", celebrity: "Beatrice (신곡)" },
  { name: "Maxine", pronunciation: "맥신", gender: "female", meaning: "가장 위대한", elements: ["metal"], personality: "위대하고 강인한", celebrity: "Maxine Waters (정치인)" },
  { name: "Isolde", pronunciation: "이졸데", gender: "female", meaning: "얼음의 전사", elements: ["metal", "water"], personality: "차갑고 아름다운", celebrity: "Isolde (트리스탄과 이졸데)" },
  { name: "Bridget", pronunciation: "브리짓", gender: "female", meaning: "강한, 높은", elements: ["metal", "fire"], personality: "강하고 열정적인", celebrity: "Bridget Jones (영화)" },
  { name: "Constance", pronunciation: "콘스탄스", gender: "female", meaning: "변치 않는, 충실한", elements: ["metal", "earth"], personality: "변치 않고 충실한", celebrity: "Constance Wu (배우)" },
  { name: "Eleanor", pronunciation: "엘리노어", gender: "female", meaning: "빛나는 자", elements: ["metal", "fire"], personality: "빛나고 고귀한", celebrity: "Eleanor Roosevelt (영부인)" },
  { name: "Harriet", pronunciation: "해리엇", gender: "female", meaning: "가정의 통치자", elements: ["metal"], personality: "통솔력 있고 강한", celebrity: "Harriet Tubman (인권운동가)" },
  { name: "Katrina", pronunciation: "카트리나", gender: "female", meaning: "순수한", elements: ["metal", "water"], personality: "순수하고 강렬한", celebrity: "Katrina (자연현상)" },
  { name: "Sabrina", pronunciation: "사브리나", gender: "female", meaning: "전설적인 공주", elements: ["metal", "wood"], personality: "전설적이고 매혹적인", celebrity: "Sabrina (영화)" },
  { name: "Cordelia", pronunciation: "코딜리아", gender: "female", meaning: "바다의 보석", elements: ["metal", "water"], personality: "아름답고 고귀한", celebrity: "Cordelia (리어왕)" },
  { name: "Winifred", pronunciation: "위니프레드", gender: "female", meaning: "평화의 친구", elements: ["metal", "earth"], personality: "평화롭고 우정 어린", celebrity: "Winifred (영화)" },

  // ── 수(水) 여자 25개 ──
  { name: "Marina", pronunciation: "마리나", gender: "female", meaning: "바다에서 온 사람", elements: ["water"], personality: "깊이 있고 신비로운", celebrity: "Marina Abramović (아티스트)" },
  { name: "Luna", pronunciation: "루나", gender: "female", meaning: "달, 밤의 빛", elements: ["water"], personality: "신비롭고 감성적인", celebrity: "Luna Lovegood (해리포터)" },
  { name: "Chloe", pronunciation: "클로이", gender: "female", meaning: "푸른 새싹, 젊은 생명력", elements: ["water", "wood"], personality: "생기 넘치고 청춘의", celebrity: "Chloe Kim (스노보드 선수)" },
  { name: "Mia", pronunciation: "미아", gender: "female", meaning: "나의 사랑, 소중한 사람", elements: ["water", "fire"], personality: "사랑스럽고 매력적인", celebrity: "Mia Farrow (배우)" },
  { name: "Isla", pronunciation: "아일라", gender: "female", meaning: "섬, 고요한 물", elements: ["water"], personality: "고요하고 평화로운", celebrity: "Isla Fisher (배우)" },
  { name: "Coral", pronunciation: "코랄", gender: "female", meaning: "산호, 바다의 보석", elements: ["water", "earth"], personality: "아름답고 깊이 있는", celebrity: "Coral (자연)" },
  { name: "Brooke", pronunciation: "브룩", gender: "female", meaning: "시냇물", elements: ["water"], personality: "맑고 청명한", celebrity: "Brooke Shields (배우)" },
  { name: "Serena", pronunciation: "세레나", gender: "female", meaning: "고요한, 평화로운", elements: ["water", "earth"], personality: "차분하고 평화로운", celebrity: "Serena Williams (테니스선수)" },
  { name: "Misty", pronunciation: "미스티", gender: "female", meaning: "안개, 신비로운", elements: ["water"], personality: "신비롭고 몽환적인", celebrity: "Misty Copeland (발레리나)" },
  { name: "Pearl", pronunciation: "펄", gender: "female", meaning: "진주, 바다의 보석", elements: ["water", "metal"], personality: "고귀하고 빛나는", celebrity: "Pearl Bailey (가수)" },
  { name: "Ariel", pronunciation: "아리엘", gender: "female", meaning: "신의 사자, 바다의 공주", elements: ["water"], personality: "자유롭고 모험적인", celebrity: "Ariel (인어공주)" },
  { name: "Rain", pronunciation: "레인", gender: "female", meaning: "비, 생명을 주는 물", elements: ["water"], personality: "생명력 있고 정화하는", celebrity: "Rain (가수)" },
  { name: "Delta", pronunciation: "델타", gender: "female", meaning: "강 삼각주", elements: ["water", "earth"], personality: "풍요롭고 비옥한", celebrity: "Delta Goodrem (가수)" },
  { name: "Nerissa", pronunciation: "네리사", gender: "female", meaning: "바다의 요정", elements: ["water"], personality: "요정같이 아름다운", celebrity: "Nerissa (베니스의 상인)" },
  { name: "Oceana", pronunciation: "오세아나", gender: "female", meaning: "바다", elements: ["water"], personality: "광대하고 깊은", celebrity: "Oceana (가수)" },
  { name: "Cascade", pronunciation: "캐스케이드", gender: "female", meaning: "폭포, 물의 흐름", elements: ["water", "wood"], personality: "역동적이고 힘찬", celebrity: "Cascade (자연)" },
  { name: "Nixie", pronunciation: "닉시", gender: "female", meaning: "물의 요정", elements: ["water"], personality: "장난스럽고 매혹적인", celebrity: "Nixie (전설 생물)" },
  { name: "Waverly", pronunciation: "웨이벌리", gender: "female", meaning: "흔들리는 초원", elements: ["water", "wood"], personality: "자유롭게 흐르는", celebrity: "Waverly (소설)" },
  { name: "Tallulah", pronunciation: "탈룰라", gender: "female", meaning: "뛰어오르는 물", elements: ["water", "fire"], personality: "활기차고 역동적인", celebrity: "Tallulah Bankhead (배우)" },
  { name: "Muriel", pronunciation: "뮤리엘", gender: "female", meaning: "빛나는 바다", elements: ["water", "fire"], personality: "빛나고 깊이 있는", celebrity: "Muriel Spark (작가)" },
  { name: "Laguna", pronunciation: "라구나", gender: "female", meaning: "석호, 고요한 물", elements: ["water", "earth"], personality: "고요하고 아름다운", celebrity: "Laguna Beach (장소)" },
  { name: "Ondine", pronunciation: "온디네", gender: "female", meaning: "물의 정령", elements: ["water"], personality: "순수하고 영적인", celebrity: "Ondine (전설)" },
  { name: "Bay", pronunciation: "베이", gender: "female", meaning: "만, 월계수", elements: ["water", "wood"], personality: "평온하고 자연적인", celebrity: "Bay (자연)" },
  { name: "Maren", pronunciation: "마렌", gender: "female", meaning: "바다의", elements: ["water"], personality: "바다처럼 깊고 넓은", celebrity: "Maren Morris (가수)" },
  { name: "Cordelia", pronunciation: "코델리아", gender: "female", meaning: "바다의 딸", elements: ["water", "metal"], personality: "고귀하고 깊이 있는", celebrity: "Cordelia (리어왕)" },

  // ── 유니섹스 10개 ──
  { name: "Phoenix", pronunciation: "피닉스", gender: "unisex", meaning: "불사조, 재탄생", elements: ["fire"], personality: "강렬하고 불굴의 의지를 가진", celebrity: "Joaquin Phoenix (배우)" },
  { name: "Morgan", pronunciation: "모건", gender: "unisex", meaning: "바다의 수호자", elements: ["water"], personality: "지혜롭고 직관적인", celebrity: "Morgan Freeman (배우)" },
  { name: "Jordan", pronunciation: "조던", gender: "unisex", meaning: "흐르는 강", elements: ["water", "earth"], personality: "역동적이고 균형 잡힌", celebrity: "Michael Jordan (농구선수)" },
  { name: "Robin", pronunciation: "로빈", gender: "unisex", meaning: "밝은 명성", elements: ["wood", "fire"], personality: "밝고 활기찬", celebrity: "Robin Williams (배우)" },
  { name: "Alex", pronunciation: "알렉스", gender: "unisex", meaning: "수호자", elements: ["metal", "earth"], personality: "보호적이고 강한", celebrity: "Alex Turner (뮤지션)" },
  { name: "Sage", pronunciation: "세이지", gender: "unisex", meaning: "현명한, 허브", elements: ["wood", "earth"], personality: "현명하고 자연적인", celebrity: "Sage (허브)" },
  { name: "River", pronunciation: "리버", gender: "unisex", meaning: "강, 흐르는 물", elements: ["water"], personality: "자유롭게 흐르는", celebrity: "River Phoenix (배우)" },
  { name: "Skyler", pronunciation: "스카일러", gender: "unisex", meaning: "하늘, 보호자", elements: ["fire", "metal"], personality: "높고 넓은 시야의", celebrity: "Skyler White (브레이킹 배드)" },
  { name: "Eden", pronunciation: "에덴", gender: "unisex", meaning: "낙원, 기쁨", elements: ["earth", "wood"], personality: "평화롭고 행복한", celebrity: "Eden (성경)" },
  { name: "Indigo", pronunciation: "인디고", gender: "unisex", meaning: "남색, 깊은 색", elements: ["water", "fire"], personality: "깊이 있고 직관적인", celebrity: "Indigo (색상)" },
];
